// Code generated by Fern. DO NOT EDIT.

package conversationactivity

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/synqly/go-sdk/client/engine/internal"
	v180 "github.com/synqly/go-sdk/client/engine/ocsf/v180"
	big "math/big"
	time "time"
)

// ActivityId is an enum, and the following values are allowed.
// 0 - Unknown: The event activity is unknown.
// 1 - List: A list of conversations was retrieved.
// 2 - Get: Details for a specific conversation were retrieved.
// 99 - Other: The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
type ActivityId = int

// CategoryUid is an enum, and the following values are allowed.
// 6 - ApplicationActivity: Application Activity events report detailed information about the behavior of applications and services.
type CategoryUid = int

// ClassUid is an enum, and the following values are allowed.
// 98906003 - ConversationActivity: Conversation Activity events report information about conversations in enterprise chat platforms, such as Microsoft Teams channels, direct messages, or AI assistant sessions.
type ClassUid = int

// Conversation Activity events report information about conversations in enterprise chat platforms, such as Microsoft Teams channels, direct messages, or AI assistant sessions.
var (
	conversationActivityFieldActivityId     = big.NewInt(1 << 0)
	conversationActivityFieldActivityName   = big.NewInt(1 << 1)
	conversationActivityFieldCategoryName   = big.NewInt(1 << 2)
	conversationActivityFieldCategoryUid    = big.NewInt(1 << 3)
	conversationActivityFieldClassUid       = big.NewInt(1 << 4)
	conversationActivityFieldConversation   = big.NewInt(1 << 5)
	conversationActivityFieldCount          = big.NewInt(1 << 6)
	conversationActivityFieldDuration       = big.NewInt(1 << 7)
	conversationActivityFieldEndTime        = big.NewInt(1 << 8)
	conversationActivityFieldEndTimeDt      = big.NewInt(1 << 9)
	conversationActivityFieldEnrichments    = big.NewInt(1 << 10)
	conversationActivityFieldMessage        = big.NewInt(1 << 11)
	conversationActivityFieldMetadata       = big.NewInt(1 << 12)
	conversationActivityFieldObservables    = big.NewInt(1 << 13)
	conversationActivityFieldRawData        = big.NewInt(1 << 14)
	conversationActivityFieldRawDataHash    = big.NewInt(1 << 15)
	conversationActivityFieldRawDataSize    = big.NewInt(1 << 16)
	conversationActivityFieldSeverity       = big.NewInt(1 << 17)
	conversationActivityFieldSeverityId     = big.NewInt(1 << 18)
	conversationActivityFieldStartTime      = big.NewInt(1 << 19)
	conversationActivityFieldStartTimeDt    = big.NewInt(1 << 20)
	conversationActivityFieldStatus         = big.NewInt(1 << 21)
	conversationActivityFieldStatusCode     = big.NewInt(1 << 22)
	conversationActivityFieldStatusDetail   = big.NewInt(1 << 23)
	conversationActivityFieldStatusId       = big.NewInt(1 << 24)
	conversationActivityFieldTime           = big.NewInt(1 << 25)
	conversationActivityFieldTimeDt         = big.NewInt(1 << 26)
	conversationActivityFieldTimezoneOffset = big.NewInt(1 << 27)
	conversationActivityFieldTypeName       = big.NewInt(1 << 28)
	conversationActivityFieldTypeUid        = big.NewInt(1 << 29)
	conversationActivityFieldUnmapped       = big.NewInt(1 << 30)
)

type ConversationActivity struct {
	// The normalized identifier of the activity that triggered the event.
	ActivityId ActivityId `json:"activity_id" url:"activity_id"`
	// The event activity name, as defined by the activity_id.
	ActivityName *string `json:"activity_name,omitempty" url:"activity_name,omitempty"`
	// The event category name, as defined by category_uid value: <code>Application Activity</code>.
	CategoryName *string `json:"category_name,omitempty" url:"category_name,omitempty"`
	// The category unique identifier of the event.
	CategoryUid CategoryUid `json:"category_uid" url:"category_uid"`
	// The unique identifier of a class. A class describes the attributes available in an event.
	ClassUid ClassUid `json:"class_uid" url:"class_uid"`
	// The details of the conversation.
	Conversation *v180.Conversation `json:"conversation" url:"conversation"`
	// The number of times that events in the same logical group occurred during the event <strong>Start Time</strong> to <strong>End Time</strong> period.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// The event duration or aggregate time, the amount of time the event covers from <code>start_time</code> to <code>end_time</code> in milliseconds.
	Duration *int `json:"duration,omitempty" url:"duration,omitempty"`
	// The end time of a time period, or the time of the most recent event included in the aggregate event.
	EndTime *v180.Timestamp `json:"end_time,omitempty" url:"end_time,omitempty"`
	// The end time of a time period, or the time of the most recent event included in the aggregate event.
	EndTimeDt *time.Time `json:"end_time_dt,omitempty" url:"end_time_dt,omitempty"`
	// The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:</p><code>[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}]</code>
	Enrichments []*v180.Enrichment `json:"enrichments,omitempty" url:"enrichments,omitempty"`
	// The description of the event/finding, as defined by the source.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// The metadata associated with the event or a finding.
	Metadata *v180.Metadata `json:"metadata" url:"metadata"`
	// The observables associated with the event or a finding.
	Observables []*v180.Observable `json:"observables,omitempty" url:"observables,omitempty"`
	// The raw event/finding data as received from the source.
	RawData *string `json:"raw_data,omitempty" url:"raw_data,omitempty"`
	// The hash, which describes the content of the raw_data field.
	RawDataHash *v180.Fingerprint `json:"raw_data_hash,omitempty" url:"raw_data_hash,omitempty"`
	// The size of the raw data which was transformed into an OCSF event, in bytes.
	RawDataSize *int `json:"raw_data_size,omitempty" url:"raw_data_size,omitempty"`
	// The event/finding severity, normalized to the caption of the <code>severity_id</code> value. In the case of 'Other', it is defined by the source.
	Severity *string `json:"severity,omitempty" url:"severity,omitempty"`
	// <p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.
	SeverityId SeverityId `json:"severity_id" url:"severity_id"`
	// The start time of a time period, or the time of the least recent event included in the aggregate event.
	StartTime *v180.Timestamp `json:"start_time,omitempty" url:"start_time,omitempty"`
	// The start time of a time period, or the time of the least recent event included in the aggregate event.
	StartTimeDt *time.Time `json:"start_time_dt,omitempty" url:"start_time_dt,omitempty"`
	// The event status, normalized to the caption of the status_id value. In the case of 'Other', it is defined by the event source.
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// The event status code, as reported by the event source.<br /><br />For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18.
	StatusCode *string `json:"status_code,omitempty" url:"status_code,omitempty"`
	// The status detail contains additional information about the event/finding outcome.
	StatusDetail *string `json:"status_detail,omitempty" url:"status_detail,omitempty"`
	// The normalized identifier of the event status.
	StatusId *StatusId `json:"status_id,omitempty" url:"status_id,omitempty"`
	// The normalized event occurrence time or the finding creation time.
	Time v180.Timestamp `json:"time" url:"time"`
	// The normalized event occurrence time or the finding creation time.
	TimeDt *time.Time `json:"time_dt,omitempty" url:"time_dt,omitempty"`
	// The number of minutes that the reported event <code>time</code> is ahead or behind UTC, in the range -1,080 to +1,080.
	TimezoneOffset *int `json:"timezone_offset,omitempty" url:"timezone_offset,omitempty"`
	// The event/finding type name, as defined by the type_uid.
	TypeName *string `json:"type_name,omitempty" url:"type_name,omitempty"`
	// The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: <code>class_uid * 100 + activity_id</code>.
	TypeUid TypeUid `json:"type_uid" url:"type_uid"`
	// The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source.
	Unmapped *v180.Object `json:"unmapped,omitempty" url:"unmapped,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConversationActivity) GetActivityId() ActivityId {
	if c == nil {
		return 0
	}
	return c.ActivityId
}

func (c *ConversationActivity) GetActivityName() *string {
	if c == nil {
		return nil
	}
	return c.ActivityName
}

func (c *ConversationActivity) GetCategoryName() *string {
	if c == nil {
		return nil
	}
	return c.CategoryName
}

func (c *ConversationActivity) GetCategoryUid() CategoryUid {
	if c == nil {
		return 0
	}
	return c.CategoryUid
}

func (c *ConversationActivity) GetClassUid() ClassUid {
	if c == nil {
		return 0
	}
	return c.ClassUid
}

func (c *ConversationActivity) GetConversation() *v180.Conversation {
	if c == nil {
		return nil
	}
	return c.Conversation
}

func (c *ConversationActivity) GetCount() *int {
	if c == nil {
		return nil
	}
	return c.Count
}

func (c *ConversationActivity) GetDuration() *int {
	if c == nil {
		return nil
	}
	return c.Duration
}

func (c *ConversationActivity) GetEndTime() *v180.Timestamp {
	if c == nil {
		return nil
	}
	return c.EndTime
}

func (c *ConversationActivity) GetEndTimeDt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndTimeDt
}

func (c *ConversationActivity) GetEnrichments() []*v180.Enrichment {
	if c == nil {
		return nil
	}
	return c.Enrichments
}

func (c *ConversationActivity) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *ConversationActivity) GetMetadata() *v180.Metadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ConversationActivity) GetObservables() []*v180.Observable {
	if c == nil {
		return nil
	}
	return c.Observables
}

func (c *ConversationActivity) GetRawData() *string {
	if c == nil {
		return nil
	}
	return c.RawData
}

func (c *ConversationActivity) GetRawDataHash() *v180.Fingerprint {
	if c == nil {
		return nil
	}
	return c.RawDataHash
}

func (c *ConversationActivity) GetRawDataSize() *int {
	if c == nil {
		return nil
	}
	return c.RawDataSize
}

func (c *ConversationActivity) GetSeverity() *string {
	if c == nil {
		return nil
	}
	return c.Severity
}

func (c *ConversationActivity) GetSeverityId() SeverityId {
	if c == nil {
		return 0
	}
	return c.SeverityId
}

func (c *ConversationActivity) GetStartTime() *v180.Timestamp {
	if c == nil {
		return nil
	}
	return c.StartTime
}

func (c *ConversationActivity) GetStartTimeDt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartTimeDt
}

func (c *ConversationActivity) GetStatus() *string {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *ConversationActivity) GetStatusCode() *string {
	if c == nil {
		return nil
	}
	return c.StatusCode
}

func (c *ConversationActivity) GetStatusDetail() *string {
	if c == nil {
		return nil
	}
	return c.StatusDetail
}

func (c *ConversationActivity) GetStatusId() *StatusId {
	if c == nil {
		return nil
	}
	return c.StatusId
}

func (c *ConversationActivity) GetTime() v180.Timestamp {
	if c == nil {
		return 0
	}
	return c.Time
}

func (c *ConversationActivity) GetTimeDt() *time.Time {
	if c == nil {
		return nil
	}
	return c.TimeDt
}

func (c *ConversationActivity) GetTimezoneOffset() *int {
	if c == nil {
		return nil
	}
	return c.TimezoneOffset
}

func (c *ConversationActivity) GetTypeName() *string {
	if c == nil {
		return nil
	}
	return c.TypeName
}

func (c *ConversationActivity) GetTypeUid() TypeUid {
	if c == nil {
		return 0
	}
	return c.TypeUid
}

func (c *ConversationActivity) GetUnmapped() *v180.Object {
	if c == nil {
		return nil
	}
	return c.Unmapped
}

func (c *ConversationActivity) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConversationActivity) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActivityId sets the ActivityId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetActivityId(activityId ActivityId) {
	c.ActivityId = activityId
	c.require(conversationActivityFieldActivityId)
}

// SetActivityName sets the ActivityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetActivityName(activityName *string) {
	c.ActivityName = activityName
	c.require(conversationActivityFieldActivityName)
}

// SetCategoryName sets the CategoryName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetCategoryName(categoryName *string) {
	c.CategoryName = categoryName
	c.require(conversationActivityFieldCategoryName)
}

// SetCategoryUid sets the CategoryUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetCategoryUid(categoryUid CategoryUid) {
	c.CategoryUid = categoryUid
	c.require(conversationActivityFieldCategoryUid)
}

// SetClassUid sets the ClassUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetClassUid(classUid ClassUid) {
	c.ClassUid = classUid
	c.require(conversationActivityFieldClassUid)
}

// SetConversation sets the Conversation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetConversation(conversation *v180.Conversation) {
	c.Conversation = conversation
	c.require(conversationActivityFieldConversation)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetCount(count *int) {
	c.Count = count
	c.require(conversationActivityFieldCount)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetDuration(duration *int) {
	c.Duration = duration
	c.require(conversationActivityFieldDuration)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetEndTime(endTime *v180.Timestamp) {
	c.EndTime = endTime
	c.require(conversationActivityFieldEndTime)
}

// SetEndTimeDt sets the EndTimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetEndTimeDt(endTimeDt *time.Time) {
	c.EndTimeDt = endTimeDt
	c.require(conversationActivityFieldEndTimeDt)
}

// SetEnrichments sets the Enrichments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetEnrichments(enrichments []*v180.Enrichment) {
	c.Enrichments = enrichments
	c.require(conversationActivityFieldEnrichments)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetMessage(message *string) {
	c.Message = message
	c.require(conversationActivityFieldMessage)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetMetadata(metadata *v180.Metadata) {
	c.Metadata = metadata
	c.require(conversationActivityFieldMetadata)
}

// SetObservables sets the Observables field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetObservables(observables []*v180.Observable) {
	c.Observables = observables
	c.require(conversationActivityFieldObservables)
}

// SetRawData sets the RawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetRawData(rawData *string) {
	c.RawData = rawData
	c.require(conversationActivityFieldRawData)
}

// SetRawDataHash sets the RawDataHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetRawDataHash(rawDataHash *v180.Fingerprint) {
	c.RawDataHash = rawDataHash
	c.require(conversationActivityFieldRawDataHash)
}

// SetRawDataSize sets the RawDataSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetRawDataSize(rawDataSize *int) {
	c.RawDataSize = rawDataSize
	c.require(conversationActivityFieldRawDataSize)
}

// SetSeverity sets the Severity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetSeverity(severity *string) {
	c.Severity = severity
	c.require(conversationActivityFieldSeverity)
}

// SetSeverityId sets the SeverityId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetSeverityId(severityId SeverityId) {
	c.SeverityId = severityId
	c.require(conversationActivityFieldSeverityId)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStartTime(startTime *v180.Timestamp) {
	c.StartTime = startTime
	c.require(conversationActivityFieldStartTime)
}

// SetStartTimeDt sets the StartTimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStartTimeDt(startTimeDt *time.Time) {
	c.StartTimeDt = startTimeDt
	c.require(conversationActivityFieldStartTimeDt)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStatus(status *string) {
	c.Status = status
	c.require(conversationActivityFieldStatus)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStatusCode(statusCode *string) {
	c.StatusCode = statusCode
	c.require(conversationActivityFieldStatusCode)
}

// SetStatusDetail sets the StatusDetail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStatusDetail(statusDetail *string) {
	c.StatusDetail = statusDetail
	c.require(conversationActivityFieldStatusDetail)
}

// SetStatusId sets the StatusId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetStatusId(statusId *StatusId) {
	c.StatusId = statusId
	c.require(conversationActivityFieldStatusId)
}

// SetTime sets the Time field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetTime(time v180.Timestamp) {
	c.Time = time
	c.require(conversationActivityFieldTime)
}

// SetTimeDt sets the TimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetTimeDt(timeDt *time.Time) {
	c.TimeDt = timeDt
	c.require(conversationActivityFieldTimeDt)
}

// SetTimezoneOffset sets the TimezoneOffset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetTimezoneOffset(timezoneOffset *int) {
	c.TimezoneOffset = timezoneOffset
	c.require(conversationActivityFieldTimezoneOffset)
}

// SetTypeName sets the TypeName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetTypeName(typeName *string) {
	c.TypeName = typeName
	c.require(conversationActivityFieldTypeName)
}

// SetTypeUid sets the TypeUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetTypeUid(typeUid TypeUid) {
	c.TypeUid = typeUid
	c.require(conversationActivityFieldTypeUid)
}

// SetUnmapped sets the Unmapped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversationActivity) SetUnmapped(unmapped *v180.Object) {
	c.Unmapped = unmapped
	c.require(conversationActivityFieldUnmapped)
}

func (c *ConversationActivity) UnmarshalJSON(data []byte) error {
	type embed ConversationActivity
	var unmarshaler = struct {
		embed
		EndTimeDt   *internal.DateTime `json:"end_time_dt,omitempty"`
		StartTimeDt *internal.DateTime `json:"start_time_dt,omitempty"`
		TimeDt      *internal.DateTime `json:"time_dt,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ConversationActivity(unmarshaler.embed)
	c.EndTimeDt = unmarshaler.EndTimeDt.TimePtr()
	c.StartTimeDt = unmarshaler.StartTimeDt.TimePtr()
	c.TimeDt = unmarshaler.TimeDt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *ConversationActivity) MarshalJSON() ([]byte, error) {
	type embed ConversationActivity
	var marshaler = struct {
		embed
		EndTimeDt   *internal.DateTime `json:"end_time_dt,omitempty"`
		StartTimeDt *internal.DateTime `json:"start_time_dt,omitempty"`
		TimeDt      *internal.DateTime `json:"time_dt,omitempty"`
	}{
		embed:       embed(*c),
		EndTimeDt:   internal.NewOptionalDateTime(c.EndTimeDt),
		StartTimeDt: internal.NewOptionalDateTime(c.StartTimeDt),
		TimeDt:      internal.NewOptionalDateTime(c.TimeDt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConversationActivity) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// SeverityId is an enum, and the following values are allowed.
// 0 - Unknown: The event/finding severity is unknown.
// 1 - Informational: Informational message. No action required.
// 2 - Low: The user decides if action is needed.
// 3 - Medium: Action is required but the situation is not serious at this time.
// 4 - High: Action is required immediately.
// 5 - Critical: Action is required immediately and the scope is broad.
// 6 - Fatal: An error occurred but it is too late to take remedial action.
// 99 - Other: The event/finding severity is not mapped. See the <code>severity</code> attribute, which contains a data source specific value.
type SeverityId = int

// StatusId is an enum, and the following values are allowed.
// 0 - Unknown: The status is unknown.
// 1 - Success
// 2 - Failure
// 99 - Other: The status is not mapped. See the <code>status</code> attribute, which contains a data source specific value.
type StatusId = int

// TypeUid is an enum, and the following values are allowed.
// 9890600300 - Unknown
// 9890600301 - List: A list of conversations was retrieved.
// 9890600302 - Get: Details for a specific conversation were retrieved.
// 9890600399 - Other
type TypeUid = int
