// Code generated by Fern. DO NOT EDIT.

package entitymanagement

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/synqly/go-sdk/client/engine/internal"
	v130 "github.com/synqly/go-sdk/client/engine/ocsf/v130"
	big "math/big"
	time "time"
)

// ActivityId is an enum, and the following values are allowed.
// 0 - Unknown: The event activity is unknown.
// 1 - Create: Create a new managed entity.
// 2 - Read: Read an existing managed entity.
// 3 - Update: Update an existing managed entity.
// 4 - Delete: Delete a managed entity.
// 5 - Move: Move or rename an existing managed entity.
// 6 - Enroll: Enroll an existing managed entity.
// 7 - Unenroll: Unenroll an existing managed entity.
// 8 - Enable: Enable an existing managed entity. Note: This is typically regarded as a semi-permanent, editor visible, syncable change.
// 9 - Disable: Disable an existing managed entity. Note: This is typically regarded as a semi-permanent, editor visible, syncable change.
// 10 - Activate: Activate an existing managed entity. Note: This is a typically regarded as a transient change, a change of state of the engine.
// 11 - Deactivate: Deactivate an existing managed entity. Note: This is a typically regarded as a transient change, a change of state of the engine.
// 12 - Suspend: Suspend an existing managed entity.
// 13 - Resume: Resume (unsuspend) an existing managed entity.
// 99 - Other: The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
type ActivityId = int

// CategoryUid is an enum, and the following values are allowed.
// 3 - AccessManagement: Identity & Access Management (IAM) events relate to the supervision of the system's authentication and access control model. Examples of such events are the success or failure of authentication, granting of authority, password change, entity change, privileged use etc.
type CategoryUid = int

// ClassUid is an enum, and the following values are allowed.
// 3004 - EntityManagement: Entity Management events report activity by a managed client, a micro service, or a user at a management console. The activity can be a create, read, update, and delete operation on a managed entity.
type ClassUid = int

// Entity Management events report activity by a managed client, a micro service, or a user at a management console. The activity can be a create, read, update, and delete operation on a managed entity.
var (
	entityManagementFieldAccessList     = big.NewInt(1 << 0)
	entityManagementFieldAccessMask     = big.NewInt(1 << 1)
	entityManagementFieldActivityId     = big.NewInt(1 << 2)
	entityManagementFieldActivityName   = big.NewInt(1 << 3)
	entityManagementFieldActor          = big.NewInt(1 << 4)
	entityManagementFieldApi            = big.NewInt(1 << 5)
	entityManagementFieldCategoryName   = big.NewInt(1 << 6)
	entityManagementFieldCategoryUid    = big.NewInt(1 << 7)
	entityManagementFieldClassUid       = big.NewInt(1 << 8)
	entityManagementFieldCloud          = big.NewInt(1 << 9)
	entityManagementFieldComment        = big.NewInt(1 << 10)
	entityManagementFieldCount          = big.NewInt(1 << 11)
	entityManagementFieldCustomFields   = big.NewInt(1 << 12)
	entityManagementFieldDevice         = big.NewInt(1 << 13)
	entityManagementFieldDuration       = big.NewInt(1 << 14)
	entityManagementFieldEndTime        = big.NewInt(1 << 15)
	entityManagementFieldEndTimeDt      = big.NewInt(1 << 16)
	entityManagementFieldEnrichments    = big.NewInt(1 << 17)
	entityManagementFieldEntity         = big.NewInt(1 << 18)
	entityManagementFieldEntityResult   = big.NewInt(1 << 19)
	entityManagementFieldHttpRequest    = big.NewInt(1 << 20)
	entityManagementFieldMessage        = big.NewInt(1 << 21)
	entityManagementFieldMetadata       = big.NewInt(1 << 22)
	entityManagementFieldObservables    = big.NewInt(1 << 23)
	entityManagementFieldOsint          = big.NewInt(1 << 24)
	entityManagementFieldRawData        = big.NewInt(1 << 25)
	entityManagementFieldSeverity       = big.NewInt(1 << 26)
	entityManagementFieldSeverityId     = big.NewInt(1 << 27)
	entityManagementFieldSrcEndpoint    = big.NewInt(1 << 28)
	entityManagementFieldStartTime      = big.NewInt(1 << 29)
	entityManagementFieldStartTimeDt    = big.NewInt(1 << 30)
	entityManagementFieldStatus         = big.NewInt(1 << 31)
	entityManagementFieldStatusCode     = big.NewInt(1 << 32)
	entityManagementFieldStatusDetail   = big.NewInt(1 << 33)
	entityManagementFieldStatusId       = big.NewInt(1 << 34)
	entityManagementFieldTime           = big.NewInt(1 << 35)
	entityManagementFieldTimeDt         = big.NewInt(1 << 36)
	entityManagementFieldTimezoneOffset = big.NewInt(1 << 37)
	entityManagementFieldTypeName       = big.NewInt(1 << 38)
	entityManagementFieldTypeUid        = big.NewInt(1 << 39)
	entityManagementFieldUnmapped       = big.NewInt(1 << 40)
)

type EntityManagement struct {
	// The list of requested access rights.
	AccessList []string `json:"access_list,omitempty" url:"access_list,omitempty"`
	// The access mask in a platform-native format.
	AccessMask *int `json:"access_mask,omitempty" url:"access_mask,omitempty"`
	// The normalized identifier of the activity that triggered the event.
	ActivityId ActivityId `json:"activity_id" url:"activity_id"`
	// The event activity name, as defined by the activity_id.
	ActivityName *string `json:"activity_name,omitempty" url:"activity_name,omitempty"`
	// Used for when the entity acting upon another entity is a process or user.
	Actor *v130.Actor `json:"actor,omitempty" url:"actor,omitempty"`
	// Describes details about a typical API (Application Programming Interface) call.
	Api *v130.Api `json:"api,omitempty" url:"api,omitempty"`
	// The event category name, as defined by category_uid value: <code>Identity & Access Management</code>.
	CategoryName *string `json:"category_name,omitempty" url:"category_name,omitempty"`
	// The category unique identifier of the event.
	CategoryUid CategoryUid `json:"category_uid" url:"category_uid"`
	// The unique identifier of a class. A class describes the attributes available in an event.
	ClassUid ClassUid `json:"class_uid" url:"class_uid"`
	// Describes details about the Cloud environment where the event was originally created or logged.
	Cloud *v130.Cloud `json:"cloud,omitempty" url:"cloud,omitempty"`
	// The user provided comment about why the entity was changed.
	Comment *string `json:"comment,omitempty" url:"comment,omitempty"`
	// The number of times that events in the same logical group occurred during the event <strong>Start Time</strong> to <strong>End Time</strong> period.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// A list of custom fields
	CustomFields *v130.Object `json:"custom_fields,omitempty" url:"custom_fields,omitempty"`
	// An addressable device, computer system or host.
	Device *v130.Device `json:"device,omitempty" url:"device,omitempty"`
	// The event duration or aggregate time, the amount of time the event covers from <code>start_time</code> to <code>end_time</code> in milliseconds.
	Duration *int `json:"duration,omitempty" url:"duration,omitempty"`
	// The end time of a time period, or the time of the most recent event included in the aggregate event.
	EndTime *v130.Timestamp `json:"end_time,omitempty" url:"end_time,omitempty"`
	// The end time of a time period, or the time of the most recent event included in the aggregate event.
	EndTimeDt *time.Time `json:"end_time_dt,omitempty" url:"end_time_dt,omitempty"`
	// The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:</p><code>[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}]</code>
	Enrichments []*v130.Enrichment `json:"enrichments,omitempty" url:"enrichments,omitempty"`
	// The managed entity that is being acted upon.
	Entity *v130.ManagedEntity `json:"entity" url:"entity"`
	// The updated managed entity.
	EntityResult *v130.ManagedEntity `json:"entity_result,omitempty" url:"entity_result,omitempty"`
	// Details about the underlying HTTP request.
	HttpRequest *v130.HttpRequest `json:"http_request,omitempty" url:"http_request,omitempty"`
	// The description of the event/finding, as defined by the source.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// The metadata associated with the event or a finding.
	Metadata *v130.Metadata `json:"metadata" url:"metadata"`
	// The observables associated with the event or a finding.
	Observables []*v130.Observable `json:"observables,omitempty" url:"observables,omitempty"`
	// The OSINT (Open Source Intelligence) object contains details related to an indicator such as the indicator itself, related indicators, geolocation, registrar information, subdomains, analyst commentary, and other contextual information. This information can be used to further enrich a detection or finding by providing decisioning support to other analysts and engineers.
	Osint []*v130.Osint `json:"osint,omitempty" url:"osint,omitempty"`
	// The raw event/finding data as received from the source.
	RawData *string `json:"raw_data,omitempty" url:"raw_data,omitempty"`
	// The event/finding severity, normalized to the caption of the severity_id value. In the case of 'Other', it is defined by the source.
	Severity *string `json:"severity,omitempty" url:"severity,omitempty"`
	// <p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.
	SeverityId SeverityId `json:"severity_id" url:"severity_id"`
	// Details about the source of the IAM activity.
	SrcEndpoint *v130.NetworkEndpoint `json:"src_endpoint,omitempty" url:"src_endpoint,omitempty"`
	// The start time of a time period, or the time of the least recent event included in the aggregate event.
	StartTime *v130.Timestamp `json:"start_time,omitempty" url:"start_time,omitempty"`
	// The start time of a time period, or the time of the least recent event included in the aggregate event.
	StartTimeDt *time.Time `json:"start_time_dt,omitempty" url:"start_time_dt,omitempty"`
	// The event status, normalized to the caption of the status_id value. In the case of 'Other', it is defined by the event source.
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// The event status code, as reported by the event source.<br /><br />For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18.
	StatusCode *string `json:"status_code,omitempty" url:"status_code,omitempty"`
	// The status detail contains additional information about the event/finding outcome.
	StatusDetail *string `json:"status_detail,omitempty" url:"status_detail,omitempty"`
	// The normalized identifier of the event status.
	StatusId *StatusId `json:"status_id,omitempty" url:"status_id,omitempty"`
	// The normalized event occurrence time or the finding creation time.
	Time v130.Timestamp `json:"time" url:"time"`
	// The normalized event occurrence time or the finding creation time.
	TimeDt *time.Time `json:"time_dt,omitempty" url:"time_dt,omitempty"`
	// The number of minutes that the reported event <code>time</code> is ahead or behind UTC, in the range -1,080 to +1,080.
	TimezoneOffset *int `json:"timezone_offset,omitempty" url:"timezone_offset,omitempty"`
	// The event/finding type name, as defined by the type_uid.
	TypeName *string `json:"type_name,omitempty" url:"type_name,omitempty"`
	// The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: <code>class_uid * 100 + activity_id</code>.
	TypeUid TypeUid `json:"type_uid" url:"type_uid"`
	// The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source.
	Unmapped *v130.Object `json:"unmapped,omitempty" url:"unmapped,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityManagement) GetAccessList() []string {
	if e == nil {
		return nil
	}
	return e.AccessList
}

func (e *EntityManagement) GetAccessMask() *int {
	if e == nil {
		return nil
	}
	return e.AccessMask
}

func (e *EntityManagement) GetActivityId() ActivityId {
	if e == nil {
		return 0
	}
	return e.ActivityId
}

func (e *EntityManagement) GetActivityName() *string {
	if e == nil {
		return nil
	}
	return e.ActivityName
}

func (e *EntityManagement) GetActor() *v130.Actor {
	if e == nil {
		return nil
	}
	return e.Actor
}

func (e *EntityManagement) GetApi() *v130.Api {
	if e == nil {
		return nil
	}
	return e.Api
}

func (e *EntityManagement) GetCategoryName() *string {
	if e == nil {
		return nil
	}
	return e.CategoryName
}

func (e *EntityManagement) GetCategoryUid() CategoryUid {
	if e == nil {
		return 0
	}
	return e.CategoryUid
}

func (e *EntityManagement) GetClassUid() ClassUid {
	if e == nil {
		return 0
	}
	return e.ClassUid
}

func (e *EntityManagement) GetCloud() *v130.Cloud {
	if e == nil {
		return nil
	}
	return e.Cloud
}

func (e *EntityManagement) GetComment() *string {
	if e == nil {
		return nil
	}
	return e.Comment
}

func (e *EntityManagement) GetCount() *int {
	if e == nil {
		return nil
	}
	return e.Count
}

func (e *EntityManagement) GetCustomFields() *v130.Object {
	if e == nil {
		return nil
	}
	return e.CustomFields
}

func (e *EntityManagement) GetDevice() *v130.Device {
	if e == nil {
		return nil
	}
	return e.Device
}

func (e *EntityManagement) GetDuration() *int {
	if e == nil {
		return nil
	}
	return e.Duration
}

func (e *EntityManagement) GetEndTime() *v130.Timestamp {
	if e == nil {
		return nil
	}
	return e.EndTime
}

func (e *EntityManagement) GetEndTimeDt() *time.Time {
	if e == nil {
		return nil
	}
	return e.EndTimeDt
}

func (e *EntityManagement) GetEnrichments() []*v130.Enrichment {
	if e == nil {
		return nil
	}
	return e.Enrichments
}

func (e *EntityManagement) GetEntity() *v130.ManagedEntity {
	if e == nil {
		return nil
	}
	return e.Entity
}

func (e *EntityManagement) GetEntityResult() *v130.ManagedEntity {
	if e == nil {
		return nil
	}
	return e.EntityResult
}

func (e *EntityManagement) GetHttpRequest() *v130.HttpRequest {
	if e == nil {
		return nil
	}
	return e.HttpRequest
}

func (e *EntityManagement) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *EntityManagement) GetMetadata() *v130.Metadata {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *EntityManagement) GetObservables() []*v130.Observable {
	if e == nil {
		return nil
	}
	return e.Observables
}

func (e *EntityManagement) GetOsint() []*v130.Osint {
	if e == nil {
		return nil
	}
	return e.Osint
}

func (e *EntityManagement) GetRawData() *string {
	if e == nil {
		return nil
	}
	return e.RawData
}

func (e *EntityManagement) GetSeverity() *string {
	if e == nil {
		return nil
	}
	return e.Severity
}

func (e *EntityManagement) GetSeverityId() SeverityId {
	if e == nil {
		return 0
	}
	return e.SeverityId
}

func (e *EntityManagement) GetSrcEndpoint() *v130.NetworkEndpoint {
	if e == nil {
		return nil
	}
	return e.SrcEndpoint
}

func (e *EntityManagement) GetStartTime() *v130.Timestamp {
	if e == nil {
		return nil
	}
	return e.StartTime
}

func (e *EntityManagement) GetStartTimeDt() *time.Time {
	if e == nil {
		return nil
	}
	return e.StartTimeDt
}

func (e *EntityManagement) GetStatus() *string {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *EntityManagement) GetStatusCode() *string {
	if e == nil {
		return nil
	}
	return e.StatusCode
}

func (e *EntityManagement) GetStatusDetail() *string {
	if e == nil {
		return nil
	}
	return e.StatusDetail
}

func (e *EntityManagement) GetStatusId() *StatusId {
	if e == nil {
		return nil
	}
	return e.StatusId
}

func (e *EntityManagement) GetTime() v130.Timestamp {
	if e == nil {
		return 0
	}
	return e.Time
}

func (e *EntityManagement) GetTimeDt() *time.Time {
	if e == nil {
		return nil
	}
	return e.TimeDt
}

func (e *EntityManagement) GetTimezoneOffset() *int {
	if e == nil {
		return nil
	}
	return e.TimezoneOffset
}

func (e *EntityManagement) GetTypeName() *string {
	if e == nil {
		return nil
	}
	return e.TypeName
}

func (e *EntityManagement) GetTypeUid() TypeUid {
	if e == nil {
		return 0
	}
	return e.TypeUid
}

func (e *EntityManagement) GetUnmapped() *v130.Object {
	if e == nil {
		return nil
	}
	return e.Unmapped
}

func (e *EntityManagement) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityManagement) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetAccessList sets the AccessList field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetAccessList(accessList []string) {
	e.AccessList = accessList
	e.require(entityManagementFieldAccessList)
}

// SetAccessMask sets the AccessMask field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetAccessMask(accessMask *int) {
	e.AccessMask = accessMask
	e.require(entityManagementFieldAccessMask)
}

// SetActivityId sets the ActivityId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetActivityId(activityId ActivityId) {
	e.ActivityId = activityId
	e.require(entityManagementFieldActivityId)
}

// SetActivityName sets the ActivityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetActivityName(activityName *string) {
	e.ActivityName = activityName
	e.require(entityManagementFieldActivityName)
}

// SetActor sets the Actor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetActor(actor *v130.Actor) {
	e.Actor = actor
	e.require(entityManagementFieldActor)
}

// SetApi sets the Api field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetApi(api *v130.Api) {
	e.Api = api
	e.require(entityManagementFieldApi)
}

// SetCategoryName sets the CategoryName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetCategoryName(categoryName *string) {
	e.CategoryName = categoryName
	e.require(entityManagementFieldCategoryName)
}

// SetCategoryUid sets the CategoryUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetCategoryUid(categoryUid CategoryUid) {
	e.CategoryUid = categoryUid
	e.require(entityManagementFieldCategoryUid)
}

// SetClassUid sets the ClassUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetClassUid(classUid ClassUid) {
	e.ClassUid = classUid
	e.require(entityManagementFieldClassUid)
}

// SetCloud sets the Cloud field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetCloud(cloud *v130.Cloud) {
	e.Cloud = cloud
	e.require(entityManagementFieldCloud)
}

// SetComment sets the Comment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetComment(comment *string) {
	e.Comment = comment
	e.require(entityManagementFieldComment)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetCount(count *int) {
	e.Count = count
	e.require(entityManagementFieldCount)
}

// SetCustomFields sets the CustomFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetCustomFields(customFields *v130.Object) {
	e.CustomFields = customFields
	e.require(entityManagementFieldCustomFields)
}

// SetDevice sets the Device field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetDevice(device *v130.Device) {
	e.Device = device
	e.require(entityManagementFieldDevice)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetDuration(duration *int) {
	e.Duration = duration
	e.require(entityManagementFieldDuration)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetEndTime(endTime *v130.Timestamp) {
	e.EndTime = endTime
	e.require(entityManagementFieldEndTime)
}

// SetEndTimeDt sets the EndTimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetEndTimeDt(endTimeDt *time.Time) {
	e.EndTimeDt = endTimeDt
	e.require(entityManagementFieldEndTimeDt)
}

// SetEnrichments sets the Enrichments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetEnrichments(enrichments []*v130.Enrichment) {
	e.Enrichments = enrichments
	e.require(entityManagementFieldEnrichments)
}

// SetEntity sets the Entity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetEntity(entity *v130.ManagedEntity) {
	e.Entity = entity
	e.require(entityManagementFieldEntity)
}

// SetEntityResult sets the EntityResult field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetEntityResult(entityResult *v130.ManagedEntity) {
	e.EntityResult = entityResult
	e.require(entityManagementFieldEntityResult)
}

// SetHttpRequest sets the HttpRequest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetHttpRequest(httpRequest *v130.HttpRequest) {
	e.HttpRequest = httpRequest
	e.require(entityManagementFieldHttpRequest)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetMessage(message *string) {
	e.Message = message
	e.require(entityManagementFieldMessage)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetMetadata(metadata *v130.Metadata) {
	e.Metadata = metadata
	e.require(entityManagementFieldMetadata)
}

// SetObservables sets the Observables field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetObservables(observables []*v130.Observable) {
	e.Observables = observables
	e.require(entityManagementFieldObservables)
}

// SetOsint sets the Osint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetOsint(osint []*v130.Osint) {
	e.Osint = osint
	e.require(entityManagementFieldOsint)
}

// SetRawData sets the RawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetRawData(rawData *string) {
	e.RawData = rawData
	e.require(entityManagementFieldRawData)
}

// SetSeverity sets the Severity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetSeverity(severity *string) {
	e.Severity = severity
	e.require(entityManagementFieldSeverity)
}

// SetSeverityId sets the SeverityId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetSeverityId(severityId SeverityId) {
	e.SeverityId = severityId
	e.require(entityManagementFieldSeverityId)
}

// SetSrcEndpoint sets the SrcEndpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetSrcEndpoint(srcEndpoint *v130.NetworkEndpoint) {
	e.SrcEndpoint = srcEndpoint
	e.require(entityManagementFieldSrcEndpoint)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStartTime(startTime *v130.Timestamp) {
	e.StartTime = startTime
	e.require(entityManagementFieldStartTime)
}

// SetStartTimeDt sets the StartTimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStartTimeDt(startTimeDt *time.Time) {
	e.StartTimeDt = startTimeDt
	e.require(entityManagementFieldStartTimeDt)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStatus(status *string) {
	e.Status = status
	e.require(entityManagementFieldStatus)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStatusCode(statusCode *string) {
	e.StatusCode = statusCode
	e.require(entityManagementFieldStatusCode)
}

// SetStatusDetail sets the StatusDetail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStatusDetail(statusDetail *string) {
	e.StatusDetail = statusDetail
	e.require(entityManagementFieldStatusDetail)
}

// SetStatusId sets the StatusId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetStatusId(statusId *StatusId) {
	e.StatusId = statusId
	e.require(entityManagementFieldStatusId)
}

// SetTime sets the Time field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetTime(time v130.Timestamp) {
	e.Time = time
	e.require(entityManagementFieldTime)
}

// SetTimeDt sets the TimeDt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetTimeDt(timeDt *time.Time) {
	e.TimeDt = timeDt
	e.require(entityManagementFieldTimeDt)
}

// SetTimezoneOffset sets the TimezoneOffset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetTimezoneOffset(timezoneOffset *int) {
	e.TimezoneOffset = timezoneOffset
	e.require(entityManagementFieldTimezoneOffset)
}

// SetTypeName sets the TypeName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetTypeName(typeName *string) {
	e.TypeName = typeName
	e.require(entityManagementFieldTypeName)
}

// SetTypeUid sets the TypeUid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetTypeUid(typeUid TypeUid) {
	e.TypeUid = typeUid
	e.require(entityManagementFieldTypeUid)
}

// SetUnmapped sets the Unmapped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityManagement) SetUnmapped(unmapped *v130.Object) {
	e.Unmapped = unmapped
	e.require(entityManagementFieldUnmapped)
}

func (e *EntityManagement) UnmarshalJSON(data []byte) error {
	type embed EntityManagement
	var unmarshaler = struct {
		embed
		EndTimeDt   *internal.DateTime `json:"end_time_dt,omitempty"`
		StartTimeDt *internal.DateTime `json:"start_time_dt,omitempty"`
		TimeDt      *internal.DateTime `json:"time_dt,omitempty"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EntityManagement(unmarshaler.embed)
	e.EndTimeDt = unmarshaler.EndTimeDt.TimePtr()
	e.StartTimeDt = unmarshaler.StartTimeDt.TimePtr()
	e.TimeDt = unmarshaler.TimeDt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = nil
	return nil
}

func (e *EntityManagement) MarshalJSON() ([]byte, error) {
	type embed EntityManagement
	var marshaler = struct {
		embed
		EndTimeDt   *internal.DateTime `json:"end_time_dt,omitempty"`
		StartTimeDt *internal.DateTime `json:"start_time_dt,omitempty"`
		TimeDt      *internal.DateTime `json:"time_dt,omitempty"`
	}{
		embed:       embed(*e),
		EndTimeDt:   internal.NewOptionalDateTime(e.EndTimeDt),
		StartTimeDt: internal.NewOptionalDateTime(e.StartTimeDt),
		TimeDt:      internal.NewOptionalDateTime(e.TimeDt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityManagement) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// SeverityId is an enum, and the following values are allowed.
// 0 - Unknown: The event/finding severity is unknown.
// 1 - Informational: Informational message. No action required.
// 2 - Low: The user decides if action is needed.
// 3 - Medium: Action is required but the situation is not serious at this time.
// 4 - High: Action is required immediately.
// 5 - Critical: Action is required immediately and the scope is broad.
// 6 - Fatal: An error occurred but it is too late to take remedial action.
// 99 - Other: The event/finding severity is not mapped. See the <code>severity</code> attribute, which contains a data source specific value.
type SeverityId = int

// StatusId is an enum, and the following values are allowed.
// 0 - Unknown: The status is unknown.
// 1 - Success
// 2 - Failure
// 99 - Other: The event status is not mapped. See the <code>status</code> attribute, which contains a data source specific value.
type StatusId = int

// TypeUid is an enum, and the following values are allowed.
// 300400 - Unknown
// 300401 - Create: Create a new managed entity.
// 300402 - Read: Read an existing managed entity.
// 300403 - Update: Update an existing managed entity.
// 300404 - Delete: Delete a managed entity.
// 300405 - Move: Move or rename an existing managed entity.
// 300406 - Enroll: Enroll an existing managed entity.
// 300407 - Unenroll: Unenroll an existing managed entity.
// 300408 - Enable: Enable an existing managed entity. Note: This is typically regarded as a semi-permanent, editor visible, syncable change.
// 300409 - Disable: Disable an existing managed entity. Note: This is typically regarded as a semi-permanent, editor visible, syncable change.
// 300410 - Activate: Activate an existing managed entity. Note: This is a typically regarded as a transient change, a change of state of the engine.
// 300411 - Deactivate: Deactivate an existing managed entity. Note: This is a typically regarded as a transient change, a change of state of the engine.
// 300412 - Suspend: Suspend an existing managed entity.
// 300413 - Resume: Resume (unsuspend) an existing managed entity.
// 300499 - Other
type TypeUid = int
