// Code generated by Fern. DO NOT EDIT.

package chat

import (
    context "context"
    http "net/http"

    engine "github.com/synqly/go-sdk/client/engine"
    core "github.com/synqly/go-sdk/client/engine/core"
    internal "github.com/synqly/go-sdk/client/engine/internal"
    option "github.com/synqly/go-sdk/client/engine/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) QueryUsers(
    ctx context.Context,
    request *engine.QueryChatUsers,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryUsersResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/chat/users"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryUsersResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryUsersResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryUserConversations(
    ctx context.Context,
    userId string,
    request *engine.QueryUserConversations,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryConversationsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/chat/users/%v/conversations",
        userId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryConversationsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryConversationsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryUserConversationMembers(
    ctx context.Context,
    userId string,
    conversationId string,
    request *engine.QueryUserConversationMembers,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryConversationMembersResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/chat/users/%v/conversations/%v/members",
        userId,
        conversationId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryConversationMembersResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryConversationMembersResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryUserConversationMessages(
    ctx context.Context,
    userId string,
    conversationId string,
    request *engine.QueryUserConversationMessages,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryMessagesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/chat/users/%v/conversations/%v/messages",
        userId,
        conversationId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryMessagesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryMessagesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryConversations(
    ctx context.Context,
    request *engine.QueryConversations,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryConversationsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/chat/conversations"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryConversationsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryConversationsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryConversationMembers(
    ctx context.Context,
    conversationId string,
    request *engine.QueryConversationMembers,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryConversationMembersResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/chat/conversations/%v/members",
        conversationId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryConversationMembersResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryConversationMembersResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryConversationMessages(
    ctx context.Context,
    conversationId string,
    request *engine.QueryConversationMessages,
    opts ...option.RequestOption,
) (*core.Response[*engine.ChatQueryMessagesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/chat/conversations/%v/messages",
        conversationId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ChatQueryMessagesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ChatQueryMessagesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

