// Code generated by Fern. DO NOT EDIT.

package accounts

import (
    context "context"

    management "github.com/synqly/go-sdk/client/management"
    core "github.com/synqly/go-sdk/client/management/core"
    internal "github.com/synqly/go-sdk/client/management/internal"
    option "github.com/synqly/go-sdk/client/management/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Returns a list of all `Account` objects. For more information on
// Organizations and Accounts, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) List(
    ctx context.Context,
    request *management.ListAccountsRequest,
    opts ...option.RequestOption,
) (*management.ListAccountsResponse, error){
    response, err := c.WithRawResponse.List(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Returns the `Account` object matching `{accountId}`. For more information on
// Organizations and Accounts, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) Get(
    ctx context.Context,
    accountId management.AccountId,
    opts ...option.RequestOption,
) (*management.GetAccountResponse, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        accountId,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Creates an `Account` object. For more information on Organizations and
// Accounts, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) Create(
    ctx context.Context,
    request *management.CreateAccountRequest,
    opts ...option.RequestOption,
) (*management.CreateAccountResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Updates the `Account` object matching `{accountId}`. For more information on
// Organizations and Accounts, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) Update(
    ctx context.Context,
    accountId management.AccountId,
    request management.UpdateAccountRequest,
    opts ...option.RequestOption,
) (*management.UpdateAccountResponse, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        accountId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Patches the `Account` object matching `{accountId}`. For more information on
// Organizations and Accounts, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) Patch(
    ctx context.Context,
    accountId management.AccountId,
    request []*management.PatchOperation,
    opts ...option.RequestOption,
) (*management.PatchAccountResponse, error){
    response, err := c.WithRawResponse.Patch(
        ctx,
        accountId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Deletes the `Account` matching `{accountId}`. Deleting an `Account` also deletea
// all `Tokens` and `Credentials` belonging to the `Account`.
func (c *Client) Delete(
    ctx context.Context,
    accountId management.AccountId,
    opts ...option.RequestOption,
) error{
    _, err := c.WithRawResponse.Delete(
        ctx,
        accountId,
        opts...,
    )
    if err != nil {
        return err
    }
    return nil
}

