// Code generated by Fern. DO NOT EDIT.

package permissionset

import (
    context "context"

    management "github.com/synqly/go-sdk/client/management"
    core "github.com/synqly/go-sdk/client/management/core"
    internal "github.com/synqly/go-sdk/client/management/internal"
    option "github.com/synqly/go-sdk/client/management/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Returns a list of all `PermissionSets` objects that match the query params.
func (c *Client) List(
    ctx context.Context,
    opts ...option.RequestOption,
) (*management.ListPermissionSetsResponse, error){
    response, err := c.WithRawResponse.List(
        ctx,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Returns the `PermissionSet` object matching `{permissionsetId}`. For more information on PermissionSets, refer to our
// [Synqly Overview](https://docs.synqly.com/docs/synqly-overview).
func (c *Client) Get(
    ctx context.Context,
    permissionsetId *management.Permissions,
    opts ...option.RequestOption,
) (*management.GetPermissionSetResponse, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        permissionsetId,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

