// Code generated by Fern. DO NOT EDIT.

package engine

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/synqly/go-sdk/client/engine/internal"
	inventoryinfo "github.com/synqly/go-sdk/client/engine/ocsf/v130/inventoryinfo"
	softwareinventoryinfo "github.com/synqly/go-sdk/client/engine/ocsf/v180/softwareinventoryinfo"
	big "math/big"
)

var (
	createDeviceRequestInputFieldMeta = big.NewInt(1 << 0)
)

type CreateDeviceRequestInput struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string            `json:"-" url:"meta,omitempty"`
	Body *CreateDeviceRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateDeviceRequestInput) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceRequestInput) SetMeta(meta []*string) {
	c.Meta = meta
	c.require(createDeviceRequestInputFieldMeta)
}

func (c *CreateDeviceRequestInput) UnmarshalJSON(data []byte) error {
	body := new(CreateDeviceRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateDeviceRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	createDevicesRequestInputFieldMeta = big.NewInt(1 << 0)
)

type CreateDevicesRequestInput struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string             `json:"-" url:"meta,omitempty"`
	Body *CreateDevicesRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateDevicesRequestInput) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesRequestInput) SetMeta(meta []*string) {
	c.Meta = meta
	c.require(createDevicesRequestInputFieldMeta)
}

func (c *CreateDevicesRequestInput) UnmarshalJSON(data []byte) error {
	body := new(CreateDevicesRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateDevicesRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	createSoftwareInventoryRequestInputFieldMeta = big.NewInt(1 << 0)
)

type CreateSoftwareInventoryRequestInput struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string                       `json:"-" url:"meta,omitempty"`
	Body *CreateSoftwareInventoryRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSoftwareInventoryRequestInput) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryRequestInput) SetMeta(meta []*string) {
	c.Meta = meta
	c.require(createSoftwareInventoryRequestInputFieldMeta)
}

func (c *CreateSoftwareInventoryRequestInput) UnmarshalJSON(data []byte) error {
	body := new(CreateSoftwareInventoryRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateSoftwareInventoryRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	getLabelsRequestFieldMeta = big.NewInt(1 << 0)
)

type GetLabelsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetLabelsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLabelsRequest) SetMeta(meta []*string) {
	g.Meta = meta
	g.require(getLabelsRequestFieldMeta)
}

var (
	queryDevicesRequestFieldMeta           = big.NewInt(1 << 0)
	queryDevicesRequestFieldLimit          = big.NewInt(1 << 1)
	queryDevicesRequestFieldCursor         = big.NewInt(1 << 2)
	queryDevicesRequestFieldFilter         = big.NewInt(1 << 3)
	queryDevicesRequestFieldOrder          = big.NewInt(1 << 4)
	queryDevicesRequestFieldIncludeRawData = big.NewInt(1 << 5)
)

type QueryDevicesRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Number of finding reports to return. Defaults to 50.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Start search from cursor position.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.
	Filter []*string `json:"-" url:"filter,omitempty"`
	// Select a field to order the results by. Defaults to `time`. To control the direction of the sorting, append
	// `[asc]` or `[desc]` to the field name. For example, `time[asc]` will sort the results by `time` in ascending order.
	// The ordering defaults to `asc` if not specified.
	Order *string `json:"-" url:"order,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QueryDevicesRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetMeta(meta []*string) {
	q.Meta = meta
	q.require(queryDevicesRequestFieldMeta)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetLimit(limit *int) {
	q.Limit = limit
	q.require(queryDevicesRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetCursor(cursor *string) {
	q.Cursor = cursor
	q.require(queryDevicesRequestFieldCursor)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetFilter(filter []*string) {
	q.Filter = filter
	q.require(queryDevicesRequestFieldFilter)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetOrder(order *string) {
	q.Order = order
	q.require(queryDevicesRequestFieldOrder)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesRequest) SetIncludeRawData(includeRawData *bool) {
	q.IncludeRawData = includeRawData
	q.require(queryDevicesRequestFieldIncludeRawData)
}

var (
	querySoftwareInventoryRequestFieldMeta           = big.NewInt(1 << 0)
	querySoftwareInventoryRequestFieldLimit          = big.NewInt(1 << 1)
	querySoftwareInventoryRequestFieldCursor         = big.NewInt(1 << 2)
	querySoftwareInventoryRequestFieldFilter         = big.NewInt(1 << 3)
	querySoftwareInventoryRequestFieldOrder          = big.NewInt(1 << 4)
	querySoftwareInventoryRequestFieldIncludeRawData = big.NewInt(1 << 5)
)

type QuerySoftwareInventoryRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Number of software inventory records to return. Defaults to 50.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Start search from cursor position.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Filter results by this query. For more information on filtering, refer to the [Assets Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.
	Filter []*string `json:"-" url:"filter,omitempty"`
	// Select a field to order the results by. Defaults to `package.name`. To control the direction of the sorting, append
	// `[asc]` or `[desc]` to the field name. For example, `package.name[asc]` will sort the results by package name in ascending order.
	// The ordering defaults to `asc` if not specified.
	Order *string `json:"-" url:"order,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QuerySoftwareInventoryRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetMeta(meta []*string) {
	q.Meta = meta
	q.require(querySoftwareInventoryRequestFieldMeta)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetLimit(limit *int) {
	q.Limit = limit
	q.require(querySoftwareInventoryRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetCursor(cursor *string) {
	q.Cursor = cursor
	q.require(querySoftwareInventoryRequestFieldCursor)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetFilter(filter []*string) {
	q.Filter = filter
	q.require(querySoftwareInventoryRequestFieldFilter)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetOrder(order *string) {
	q.Order = order
	q.require(querySoftwareInventoryRequestFieldOrder)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryRequest) SetIncludeRawData(includeRawData *bool) {
	q.IncludeRawData = includeRawData
	q.require(querySoftwareInventoryRequestFieldIncludeRawData)
}

var (
	createDeviceRequestFieldDevice     = big.NewInt(1 << 0)
	createDeviceRequestFieldSourceName = big.NewInt(1 << 1)
)

type CreateDeviceRequest struct {
	Device Device `json:"device" url:"device"`
	// Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
	// Omit or leave empty when the integration does not use it; some integrations require it.
	SourceName *string `json:"source_name,omitempty" url:"source_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDeviceRequest) GetDevice() Device {
	if c == nil {
		return nil
	}
	return c.Device
}

func (c *CreateDeviceRequest) GetSourceName() *string {
	if c == nil {
		return nil
	}
	return c.SourceName
}

func (c *CreateDeviceRequest) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateDeviceRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDevice sets the Device field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceRequest) SetDevice(device Device) {
	c.Device = device
	c.require(createDeviceRequestFieldDevice)
}

// SetSourceName sets the SourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceRequest) SetSourceName(sourceName *string) {
	c.SourceName = sourceName
	c.require(createDeviceRequestFieldSourceName)
}

func (c *CreateDeviceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDeviceRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDeviceRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateDeviceRequest) MarshalJSON() ([]byte, error) {
	type embed CreateDeviceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateDeviceRequest) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createDeviceResponseFieldMessages = big.NewInt(1 << 0)
	createDeviceResponseFieldMeta     = big.NewInt(1 << 1)
	createDeviceResponseFieldDevice   = big.NewInt(1 << 2)
)

type CreateDeviceResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta   *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	Device Device        `json:"device" url:"device"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDeviceResponse) GetMessages() *MessagesResponse {
	if c == nil {
		return nil
	}
	return c.Messages
}

func (c *CreateDeviceResponse) GetMeta() *MetaResponse {
	if c == nil {
		return nil
	}
	return c.Meta
}

func (c *CreateDeviceResponse) GetDevice() Device {
	if c == nil {
		return nil
	}
	return c.Device
}

func (c *CreateDeviceResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateDeviceResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceResponse) SetMessages(messages *MessagesResponse) {
	c.Messages = messages
	c.require(createDeviceResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceResponse) SetMeta(meta *MetaResponse) {
	c.Meta = meta
	c.require(createDeviceResponseFieldMeta)
}

// SetDevice sets the Device field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDeviceResponse) SetDevice(device Device) {
	c.Device = device
	c.require(createDeviceResponseFieldDevice)
}

func (c *CreateDeviceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDeviceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDeviceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateDeviceResponse) MarshalJSON() ([]byte, error) {
	type embed CreateDeviceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateDeviceResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createDevicesRequestFieldDevices          = big.NewInt(1 << 0)
	createDevicesRequestFieldCustomProperties = big.NewInt(1 << 1)
	createDevicesRequestFieldSourceName       = big.NewInt(1 << 2)
)

type CreateDevicesRequest struct {
	Devices          []Device          `json:"devices" url:"devices"`
	CustomProperties map[string]string `json:"custom_properties,omitempty" url:"custom_properties,omitempty"`
	// Connector hint passed to the integration (for example ServiceNow discovery_source with Identify & Reconcile).
	SourceName string `json:"source_name" url:"source_name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDevicesRequest) GetDevices() []Device {
	if c == nil {
		return nil
	}
	return c.Devices
}

func (c *CreateDevicesRequest) GetCustomProperties() map[string]string {
	if c == nil {
		return nil
	}
	return c.CustomProperties
}

func (c *CreateDevicesRequest) GetSourceName() string {
	if c == nil {
		return ""
	}
	return c.SourceName
}

func (c *CreateDevicesRequest) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateDevicesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDevices sets the Devices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesRequest) SetDevices(devices []Device) {
	c.Devices = devices
	c.require(createDevicesRequestFieldDevices)
}

// SetCustomProperties sets the CustomProperties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesRequest) SetCustomProperties(customProperties map[string]string) {
	c.CustomProperties = customProperties
	c.require(createDevicesRequestFieldCustomProperties)
}

// SetSourceName sets the SourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesRequest) SetSourceName(sourceName string) {
	c.SourceName = sourceName
	c.require(createDevicesRequestFieldSourceName)
}

func (c *CreateDevicesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDevicesRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDevicesRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateDevicesRequest) MarshalJSON() ([]byte, error) {
	type embed CreateDevicesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateDevicesRequest) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createDevicesResponseFieldMessages = big.NewInt(1 << 0)
	createDevicesResponseFieldMeta     = big.NewInt(1 << 1)
	createDevicesResponseFieldStatus   = big.NewInt(1 << 2)
	createDevicesResponseFieldErrors   = big.NewInt(1 << 3)
)

type CreateDevicesResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Specifies the status of the bulk create devices job, which can be COMPLETE or PENDING.
	Status QueryStatus `json:"status" url:"status"`
	// Provides additional details about any errors encountered during the bulk create operation.
	Errors *Problem `json:"errors,omitempty" url:"errors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDevicesResponse) GetMessages() *MessagesResponse {
	if c == nil {
		return nil
	}
	return c.Messages
}

func (c *CreateDevicesResponse) GetMeta() *MetaResponse {
	if c == nil {
		return nil
	}
	return c.Meta
}

func (c *CreateDevicesResponse) GetStatus() QueryStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateDevicesResponse) GetErrors() *Problem {
	if c == nil {
		return nil
	}
	return c.Errors
}

func (c *CreateDevicesResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateDevicesResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesResponse) SetMessages(messages *MessagesResponse) {
	c.Messages = messages
	c.require(createDevicesResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesResponse) SetMeta(meta *MetaResponse) {
	c.Meta = meta
	c.require(createDevicesResponseFieldMeta)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesResponse) SetStatus(status QueryStatus) {
	c.Status = status
	c.require(createDevicesResponseFieldStatus)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateDevicesResponse) SetErrors(errors *Problem) {
	c.Errors = errors
	c.require(createDevicesResponseFieldErrors)
}

func (c *CreateDevicesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDevicesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDevicesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateDevicesResponse) MarshalJSON() ([]byte, error) {
	type embed CreateDevicesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateDevicesResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSoftwareInventoryRequestFieldSoftwareInventory = big.NewInt(1 << 0)
	createSoftwareInventoryRequestFieldSourceName        = big.NewInt(1 << 1)
)

type CreateSoftwareInventoryRequest struct {
	SoftwareInventory SoftwareInventory `json:"software_inventory" url:"software_inventory"`
	// Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
	// Omit or leave empty when the integration does not use it; some integrations require it.
	SourceName *string `json:"source_name,omitempty" url:"source_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSoftwareInventoryRequest) GetSoftwareInventory() SoftwareInventory {
	if c == nil {
		return nil
	}
	return c.SoftwareInventory
}

func (c *CreateSoftwareInventoryRequest) GetSourceName() *string {
	if c == nil {
		return nil
	}
	return c.SourceName
}

func (c *CreateSoftwareInventoryRequest) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSoftwareInventoryRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSoftwareInventory sets the SoftwareInventory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryRequest) SetSoftwareInventory(softwareInventory SoftwareInventory) {
	c.SoftwareInventory = softwareInventory
	c.require(createSoftwareInventoryRequestFieldSoftwareInventory)
}

// SetSourceName sets the SourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryRequest) SetSourceName(sourceName *string) {
	c.SourceName = sourceName
	c.require(createSoftwareInventoryRequestFieldSourceName)
}

func (c *CreateSoftwareInventoryRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSoftwareInventoryRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSoftwareInventoryRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateSoftwareInventoryRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSoftwareInventoryRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSoftwareInventoryRequest) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSoftwareInventoryResponseFieldMessages          = big.NewInt(1 << 0)
	createSoftwareInventoryResponseFieldMeta              = big.NewInt(1 << 1)
	createSoftwareInventoryResponseFieldSoftwareInventory = big.NewInt(1 << 2)
)

type CreateSoftwareInventoryResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta              *MetaResponse     `json:"meta,omitempty" url:"meta,omitempty"`
	SoftwareInventory SoftwareInventory `json:"software_inventory" url:"software_inventory"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSoftwareInventoryResponse) GetMessages() *MessagesResponse {
	if c == nil {
		return nil
	}
	return c.Messages
}

func (c *CreateSoftwareInventoryResponse) GetMeta() *MetaResponse {
	if c == nil {
		return nil
	}
	return c.Meta
}

func (c *CreateSoftwareInventoryResponse) GetSoftwareInventory() SoftwareInventory {
	if c == nil {
		return nil
	}
	return c.SoftwareInventory
}

func (c *CreateSoftwareInventoryResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSoftwareInventoryResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryResponse) SetMessages(messages *MessagesResponse) {
	c.Messages = messages
	c.require(createSoftwareInventoryResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryResponse) SetMeta(meta *MetaResponse) {
	c.Meta = meta
	c.require(createSoftwareInventoryResponseFieldMeta)
}

// SetSoftwareInventory sets the SoftwareInventory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSoftwareInventoryResponse) SetSoftwareInventory(softwareInventory SoftwareInventory) {
	c.SoftwareInventory = softwareInventory
	c.require(createSoftwareInventoryResponseFieldSoftwareInventory)
}

func (c *CreateSoftwareInventoryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSoftwareInventoryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSoftwareInventoryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CreateSoftwareInventoryResponse) MarshalJSON() ([]byte, error) {
	type embed CreateSoftwareInventoryResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSoftwareInventoryResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Device inventory information. Represented by OCSF Device Inventory Info class (class_uid 5001).
type Device = *inventoryinfo.InventoryInfo

var (
	getLabelsResponseFieldMessages = big.NewInt(1 << 0)
	getLabelsResponseFieldMeta     = big.NewInt(1 << 1)
	getLabelsResponseFieldCursor   = big.NewInt(1 << 2)
	getLabelsResponseFieldResult   = big.NewInt(1 << 3)
)

type GetLabelsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string   `json:"cursor" url:"cursor"`
	Result []*Label `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetLabelsResponse) GetMessages() *MessagesResponse {
	if g == nil {
		return nil
	}
	return g.Messages
}

func (g *GetLabelsResponse) GetMeta() *MetaResponse {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetLabelsResponse) GetCursor() string {
	if g == nil {
		return ""
	}
	return g.Cursor
}

func (g *GetLabelsResponse) GetResult() []*Label {
	if g == nil {
		return nil
	}
	return g.Result
}

func (g *GetLabelsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetLabelsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLabelsResponse) SetMessages(messages *MessagesResponse) {
	g.Messages = messages
	g.require(getLabelsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLabelsResponse) SetMeta(meta *MetaResponse) {
	g.Meta = meta
	g.require(getLabelsResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLabelsResponse) SetCursor(cursor string) {
	g.Cursor = cursor
	g.require(getLabelsResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetLabelsResponse) SetResult(result []*Label) {
	g.Result = result
	g.require(getLabelsResponseFieldResult)
}

func (g *GetLabelsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetLabelsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetLabelsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = nil
	return nil
}

func (g *GetLabelsResponse) MarshalJSON() ([]byte, error) {
	type embed GetLabelsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetLabelsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	labelFieldKey   = big.NewInt(1 << 0)
	labelFieldValue = big.NewInt(1 << 1)
)

type Label struct {
	Key   *string `json:"key,omitempty" url:"key,omitempty"`
	Value string  `json:"value" url:"value"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *Label) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *Label) GetValue() string {
	if l == nil {
		return ""
	}
	return l.Value
}

func (l *Label) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *Label) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *Label) SetKey(key *string) {
	l.Key = key
	l.require(labelFieldKey)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *Label) SetValue(value string) {
	l.Value = value
	l.require(labelFieldValue)
}

func (l *Label) UnmarshalJSON(data []byte) error {
	type unmarshaler Label
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = Label(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = nil
	return nil
}

func (l *Label) MarshalJSON() ([]byte, error) {
	type embed Label
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *Label) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	queryDevicesResponseFieldMessages = big.NewInt(1 << 0)
	queryDevicesResponseFieldMeta     = big.NewInt(1 << 1)
	queryDevicesResponseFieldCursor   = big.NewInt(1 << 2)
	queryDevicesResponseFieldResult   = big.NewInt(1 << 3)
)

type QueryDevicesResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string   `json:"cursor" url:"cursor"`
	Result []Device `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QueryDevicesResponse) GetMessages() *MessagesResponse {
	if q == nil {
		return nil
	}
	return q.Messages
}

func (q *QueryDevicesResponse) GetMeta() *MetaResponse {
	if q == nil {
		return nil
	}
	return q.Meta
}

func (q *QueryDevicesResponse) GetCursor() string {
	if q == nil {
		return ""
	}
	return q.Cursor
}

func (q *QueryDevicesResponse) GetResult() []Device {
	if q == nil {
		return nil
	}
	return q.Result
}

func (q *QueryDevicesResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QueryDevicesResponse) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesResponse) SetMessages(messages *MessagesResponse) {
	q.Messages = messages
	q.require(queryDevicesResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesResponse) SetMeta(meta *MetaResponse) {
	q.Meta = meta
	q.require(queryDevicesResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesResponse) SetCursor(cursor string) {
	q.Cursor = cursor
	q.require(queryDevicesResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDevicesResponse) SetResult(result []Device) {
	q.Result = result
	q.require(queryDevicesResponseFieldResult)
}

func (q *QueryDevicesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler QueryDevicesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QueryDevicesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = nil
	return nil
}

func (q *QueryDevicesResponse) MarshalJSON() ([]byte, error) {
	type embed QueryDevicesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QueryDevicesResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	querySoftwareInventoryResponseFieldMessages = big.NewInt(1 << 0)
	querySoftwareInventoryResponseFieldMeta     = big.NewInt(1 << 1)
	querySoftwareInventoryResponseFieldCursor   = big.NewInt(1 << 2)
	querySoftwareInventoryResponseFieldResult   = big.NewInt(1 << 3)
)

type QuerySoftwareInventoryResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string              `json:"cursor" url:"cursor"`
	Result []SoftwareInventory `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuerySoftwareInventoryResponse) GetMessages() *MessagesResponse {
	if q == nil {
		return nil
	}
	return q.Messages
}

func (q *QuerySoftwareInventoryResponse) GetMeta() *MetaResponse {
	if q == nil {
		return nil
	}
	return q.Meta
}

func (q *QuerySoftwareInventoryResponse) GetCursor() string {
	if q == nil {
		return ""
	}
	return q.Cursor
}

func (q *QuerySoftwareInventoryResponse) GetResult() []SoftwareInventory {
	if q == nil {
		return nil
	}
	return q.Result
}

func (q *QuerySoftwareInventoryResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuerySoftwareInventoryResponse) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryResponse) SetMessages(messages *MessagesResponse) {
	q.Messages = messages
	q.require(querySoftwareInventoryResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryResponse) SetMeta(meta *MetaResponse) {
	q.Meta = meta
	q.require(querySoftwareInventoryResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryResponse) SetCursor(cursor string) {
	q.Cursor = cursor
	q.require(querySoftwareInventoryResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySoftwareInventoryResponse) SetResult(result []SoftwareInventory) {
	q.Result = result
	q.require(querySoftwareInventoryResponseFieldResult)
}

func (q *QuerySoftwareInventoryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler QuerySoftwareInventoryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuerySoftwareInventoryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = nil
	return nil
}

func (q *QuerySoftwareInventoryResponse) MarshalJSON() ([]byte, error) {
	type embed QuerySoftwareInventoryResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuerySoftwareInventoryResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

// Software inventory information for an asset management system. Represented by OCSF v1.8.0 Software Inventory Info (class_uid 5020) using the OCSF Synqly extension and the OCSF Date/Time profile. The `package` or `sbom` object describes installed software; `device` links the record to a host or configuration item.
type SoftwareInventory = *softwareinventoryinfo.SoftwareInfo
