// Code generated by Fern. DO NOT EDIT.

package engine

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/synqly/go-sdk/v2/client/engine/internal"
	latest "github.com/synqly/go-sdk/v2/client/engine/ocsf/latest"
	big "math/big"
)

var (
	securityAwarenessGetPhishingSimulationDetailsRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessGetPhishingSimulationDetailsRequestFieldIncludeRawData = big.NewInt(1 << 1)
)

type SecurityAwarenessGetPhishingSimulationDetailsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetPhishingSimulationDetailsRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessGetPhishingSimulationDetailsRequestFieldMeta)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetPhishingSimulationDetailsRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessGetPhishingSimulationDetailsRequestFieldIncludeRawData)
}

var (
	securityAwarenessGetTrainingCampaignDetailsRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessGetTrainingCampaignDetailsRequestFieldIncludeRawData = big.NewInt(1 << 1)
)

type SecurityAwarenessGetTrainingCampaignDetailsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetTrainingCampaignDetailsRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessGetTrainingCampaignDetailsRequestFieldMeta)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetTrainingCampaignDetailsRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessGetTrainingCampaignDetailsRequestFieldIncludeRawData)
}

var (
	securityAwarenessGetUserDetailsRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessGetUserDetailsRequestFieldIncludeRawData = big.NewInt(1 << 1)
)

type SecurityAwarenessGetUserDetailsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessGetUserDetailsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetUserDetailsRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessGetUserDetailsRequestFieldMeta)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetUserDetailsRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessGetUserDetailsRequestFieldIncludeRawData)
}

var (
	securityAwarenessQueryPhishingSimulationsRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessQueryPhishingSimulationsRequestFieldLimit          = big.NewInt(1 << 1)
	securityAwarenessQueryPhishingSimulationsRequestFieldFilter         = big.NewInt(1 << 2)
	securityAwarenessQueryPhishingSimulationsRequestFieldCursor         = big.NewInt(1 << 3)
	securityAwarenessQueryPhishingSimulationsRequestFieldIncludeRawData = big.NewInt(1 << 4)
)

type SecurityAwarenessQueryPhishingSimulationsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Number of phishing simulations to return. Defaults to 100 with a maximum of 1000. If a provider has a maximum limit lower than 1000, the provider's maximum limit will be used instead.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/security-awareness/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.
	Filter []*string `json:"-" url:"filter,omitempty"`
	// Start search from cursor position.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessQueryPhishingSimulationsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessQueryPhishingSimulationsRequestFieldMeta)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(securityAwarenessQueryPhishingSimulationsRequestFieldLimit)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsRequest) SetFilter(filter []*string) {
	s.Filter = filter
	s.require(securityAwarenessQueryPhishingSimulationsRequestFieldFilter)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryPhishingSimulationsRequestFieldCursor)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessQueryPhishingSimulationsRequestFieldIncludeRawData)
}

var (
	securityAwarenessQueryTrainingCampaignsRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessQueryTrainingCampaignsRequestFieldLimit          = big.NewInt(1 << 1)
	securityAwarenessQueryTrainingCampaignsRequestFieldFilter         = big.NewInt(1 << 2)
	securityAwarenessQueryTrainingCampaignsRequestFieldCursor         = big.NewInt(1 << 3)
	securityAwarenessQueryTrainingCampaignsRequestFieldIncludeRawData = big.NewInt(1 << 4)
)

type SecurityAwarenessQueryTrainingCampaignsRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Number of training campaigns to return. Defaults to 100 with a maximum of 1000. If a provider has a maximum limit lower than 1000, the provider's maximum limit will be used instead.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/security-awareness/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.
	Filter []*string `json:"-" url:"filter,omitempty"`
	// Start search from cursor position.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessQueryTrainingCampaignsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessQueryTrainingCampaignsRequestFieldMeta)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(securityAwarenessQueryTrainingCampaignsRequestFieldLimit)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsRequest) SetFilter(filter []*string) {
	s.Filter = filter
	s.require(securityAwarenessQueryTrainingCampaignsRequestFieldFilter)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryTrainingCampaignsRequestFieldCursor)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessQueryTrainingCampaignsRequestFieldIncludeRawData)
}

var (
	securityAwarenessQueryUsersRequestFieldMeta           = big.NewInt(1 << 0)
	securityAwarenessQueryUsersRequestFieldLimit          = big.NewInt(1 << 1)
	securityAwarenessQueryUsersRequestFieldFilter         = big.NewInt(1 << 2)
	securityAwarenessQueryUsersRequestFieldCursor         = big.NewInt(1 << 3)
	securityAwarenessQueryUsersRequestFieldIncludeRawData = big.NewInt(1 << 4)
)

type SecurityAwarenessQueryUsersRequest struct {
	// Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.
	Meta []*string `json:"-" url:"meta,omitempty"`
	// Number of users to return. Defaults to 100 with a maximum of 1000. If a provider has a maximum limit lower than 1000, the provider's maximum limit will be used instead.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/security-awareness/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.
	Filter []*string `json:"-" url:"filter,omitempty"`
	// Start search from cursor position.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Include the raw data from the provider in the response. Defaults to `false`.
	IncludeRawData *bool `json:"-" url:"include_raw_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SecurityAwarenessQueryUsersRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersRequest) SetMeta(meta []*string) {
	s.Meta = meta
	s.require(securityAwarenessQueryUsersRequestFieldMeta)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(securityAwarenessQueryUsersRequestFieldLimit)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersRequest) SetFilter(filter []*string) {
	s.Filter = filter
	s.require(securityAwarenessQueryUsersRequestFieldFilter)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryUsersRequestFieldCursor)
}

// SetIncludeRawData sets the IncludeRawData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersRequest) SetIncludeRawData(includeRawData *bool) {
	s.IncludeRawData = includeRawData
	s.require(securityAwarenessQueryUsersRequestFieldIncludeRawData)
}

var (
	securityAwarenessGetPhishingSimulationDetailsResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessGetPhishingSimulationDetailsResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessGetPhishingSimulationDetailsResponseFieldResult   = big.NewInt(1 << 2)
)

type SecurityAwarenessGetPhishingSimulationDetailsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// The details of the phishing simulation.
	Result latest.PhishingSimulationInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) GetResult() latest.PhishingSimulationInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessGetPhishingSimulationDetailsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessGetPhishingSimulationDetailsResponseFieldMeta)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) SetResult(result latest.PhishingSimulationInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessGetPhishingSimulationDetailsResponseFieldResult)
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessGetPhishingSimulationDetailsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessGetPhishingSimulationDetailsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessGetPhishingSimulationDetailsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessGetPhishingSimulationDetailsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	securityAwarenessGetTrainingCampaignDetailsResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessGetTrainingCampaignDetailsResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessGetTrainingCampaignDetailsResponseFieldResult   = big.NewInt(1 << 2)
)

type SecurityAwarenessGetTrainingCampaignDetailsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// The details of the training campaign.
	Result latest.TrainingCampaignInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) GetResult() latest.TrainingCampaignInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessGetTrainingCampaignDetailsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessGetTrainingCampaignDetailsResponseFieldMeta)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) SetResult(result latest.TrainingCampaignInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessGetTrainingCampaignDetailsResponseFieldResult)
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessGetTrainingCampaignDetailsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessGetTrainingCampaignDetailsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessGetTrainingCampaignDetailsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessGetTrainingCampaignDetailsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	securityAwarenessGetUserDetailsResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessGetUserDetailsResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessGetUserDetailsResponseFieldResult   = big.NewInt(1 << 2)
)

type SecurityAwarenessGetUserDetailsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// The details of the user.
	Result latest.UserInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessGetUserDetailsResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessGetUserDetailsResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessGetUserDetailsResponse) GetResult() latest.UserInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessGetUserDetailsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessGetUserDetailsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetUserDetailsResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessGetUserDetailsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetUserDetailsResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessGetUserDetailsResponseFieldMeta)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessGetUserDetailsResponse) SetResult(result latest.UserInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessGetUserDetailsResponseFieldResult)
}

func (s *SecurityAwarenessGetUserDetailsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessGetUserDetailsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessGetUserDetailsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessGetUserDetailsResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessGetUserDetailsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessGetUserDetailsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	securityAwarenessQueryPhishingSimulationsResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessQueryPhishingSimulationsResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessQueryPhishingSimulationsResponseFieldCursor   = big.NewInt(1 << 2)
	securityAwarenessQueryPhishingSimulationsResponseFieldResult   = big.NewInt(1 << 3)
)

type SecurityAwarenessQueryPhishingSimulationsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string `json:"cursor" url:"cursor"`
	// List of phishing simulations that match the query.
	Result []latest.PhishingSimulationInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) GetCursor() string {
	if s == nil {
		return ""
	}
	return s.Cursor
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) GetResult() []latest.PhishingSimulationInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessQueryPhishingSimulationsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessQueryPhishingSimulationsResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsResponse) SetCursor(cursor string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryPhishingSimulationsResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryPhishingSimulationsResponse) SetResult(result []latest.PhishingSimulationInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessQueryPhishingSimulationsResponseFieldResult)
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessQueryPhishingSimulationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessQueryPhishingSimulationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessQueryPhishingSimulationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessQueryPhishingSimulationsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	securityAwarenessQueryTrainingCampaignsResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessQueryTrainingCampaignsResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessQueryTrainingCampaignsResponseFieldCursor   = big.NewInt(1 << 2)
	securityAwarenessQueryTrainingCampaignsResponseFieldResult   = big.NewInt(1 << 3)
)

type SecurityAwarenessQueryTrainingCampaignsResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string `json:"cursor" url:"cursor"`
	// List of training campaigns that match the query.
	Result []latest.TrainingCampaignInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) GetCursor() string {
	if s == nil {
		return ""
	}
	return s.Cursor
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) GetResult() []latest.TrainingCampaignInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessQueryTrainingCampaignsResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessQueryTrainingCampaignsResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsResponse) SetCursor(cursor string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryTrainingCampaignsResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryTrainingCampaignsResponse) SetResult(result []latest.TrainingCampaignInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessQueryTrainingCampaignsResponseFieldResult)
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessQueryTrainingCampaignsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessQueryTrainingCampaignsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessQueryTrainingCampaignsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessQueryTrainingCampaignsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	securityAwarenessQueryUsersResponseFieldMessages = big.NewInt(1 << 0)
	securityAwarenessQueryUsersResponseFieldMeta     = big.NewInt(1 << 1)
	securityAwarenessQueryUsersResponseFieldCursor   = big.NewInt(1 << 2)
	securityAwarenessQueryUsersResponseFieldResult   = big.NewInt(1 << 3)
)

type SecurityAwarenessQueryUsersResponse struct {
	// Additional messages from the service response that may be helpful to the client.
	Messages *MessagesResponse `json:"messages,omitempty" url:"messages,omitempty"`
	// Various metadata about the results organized by group, then type, then field.
	Meta *MetaResponse `json:"meta,omitempty" url:"meta,omitempty"`
	// Cursor to use to retrieve the next page of results
	Cursor string `json:"cursor" url:"cursor"`
	// List of users that match the query.
	Result []latest.UserInventoryInfo `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SecurityAwarenessQueryUsersResponse) GetMessages() *MessagesResponse {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *SecurityAwarenessQueryUsersResponse) GetMeta() *MetaResponse {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SecurityAwarenessQueryUsersResponse) GetCursor() string {
	if s == nil {
		return ""
	}
	return s.Cursor
}

func (s *SecurityAwarenessQueryUsersResponse) GetResult() []latest.UserInventoryInfo {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SecurityAwarenessQueryUsersResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SecurityAwarenessQueryUsersResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersResponse) SetMessages(messages *MessagesResponse) {
	s.Messages = messages
	s.require(securityAwarenessQueryUsersResponseFieldMessages)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersResponse) SetMeta(meta *MetaResponse) {
	s.Meta = meta
	s.require(securityAwarenessQueryUsersResponseFieldMeta)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersResponse) SetCursor(cursor string) {
	s.Cursor = cursor
	s.require(securityAwarenessQueryUsersResponseFieldCursor)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SecurityAwarenessQueryUsersResponse) SetResult(result []latest.UserInventoryInfo) {
	s.Result = result
	s.require(securityAwarenessQueryUsersResponseFieldResult)
}

func (s *SecurityAwarenessQueryUsersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SecurityAwarenessQueryUsersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SecurityAwarenessQueryUsersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = nil
	return nil
}

func (s *SecurityAwarenessQueryUsersResponse) MarshalJSON() ([]byte, error) {
	type embed SecurityAwarenessQueryUsersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SecurityAwarenessQueryUsersResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
