// Code generated by Fern. DO NOT EDIT.

package stix

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/synqly/go-sdk/client/engine/internal"
	big "math/big"
	time "time"
)

var (
	commonPropertiesFieldId                 = big.NewInt(1 << 0)
	commonPropertiesFieldCreatedByRef       = big.NewInt(1 << 1)
	commonPropertiesFieldCreated            = big.NewInt(1 << 2)
	commonPropertiesFieldModified           = big.NewInt(1 << 3)
	commonPropertiesFieldRevoked            = big.NewInt(1 << 4)
	commonPropertiesFieldLabels             = big.NewInt(1 << 5)
	commonPropertiesFieldConfidence         = big.NewInt(1 << 6)
	commonPropertiesFieldLang               = big.NewInt(1 << 7)
	commonPropertiesFieldExternalReferences = big.NewInt(1 << 8)
	commonPropertiesFieldObjectMarkingRefs  = big.NewInt(1 << 9)
	commonPropertiesFieldGranularMarkings   = big.NewInt(1 << 10)
	commonPropertiesFieldExtensions         = big.NewInt(1 << 11)
)

type CommonProperties struct {
	// The id property uniquely identifies this object.
	Id Id `json:"id" url:"id"`
	// The created_by_ref property specifies the id property of the identity object that describes the entity that created this object.
	CreatedByRef *Identity `json:"created_by_ref,omitempty" url:"created_by_ref,omitempty"`
	// The created property represents the time at which the object was originally created.
	Created time.Time `json:"created" url:"created"`
	// The modified property is only used by STIX Objects that support versioning and represents the time that this particular version of the object was last modified.
	Modified time.Time `json:"modified" url:"modified"`
	// The revoked property indicates whether this object has been revoked. If the revoked property is present and set to true, then the object has been revoked.
	Revoked *bool `json:"revoked,omitempty" url:"revoked,omitempty"`
	// The labels property is an array of strings that are used to categorize this object.
	Labels []string `json:"labels,omitempty" url:"labels,omitempty"`
	// The confidence property is an integer from 0 to 100 that represents the confidence that this object is accurate and valid.
	Confidence *int `json:"confidence,omitempty" url:"confidence,omitempty"`
	// The lang property specifies the language used in the properties of the object.
	Lang *string `json:"lang,omitempty" url:"lang,omitempty"`
	// The external_references property is an array of external references that are relevant to this object.
	ExternalReferences []*ExternalReference `json:"external_references,omitempty" url:"external_references,omitempty"`
	// The object_marking_refs property is an array of ids of marking_definition objects that apply to this object.
	ObjectMarkingRefs []*MarkingDefinition `json:"object_marking_refs,omitempty" url:"object_marking_refs,omitempty"`
	// The granular_markings property is an array of granular markings that are applied to this object.
	GranularMarkings []*GranularMarking `json:"granular_markings,omitempty" url:"granular_markings,omitempty"`
	// The extensions property is an object that contains custom properties or objects that extend the object.
	Extensions map[string]any `json:"extensions,omitempty" url:"extensions,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	specVersion    string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommonProperties) GetId() Id {
	if c == nil {
		return ""
	}
	return c.Id
}

func (c *CommonProperties) GetCreatedByRef() *Identity {
	if c == nil {
		return nil
	}
	return c.CreatedByRef
}

func (c *CommonProperties) GetCreated() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Created
}

func (c *CommonProperties) GetModified() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Modified
}

func (c *CommonProperties) GetRevoked() *bool {
	if c == nil {
		return nil
	}
	return c.Revoked
}

func (c *CommonProperties) GetLabels() []string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CommonProperties) GetConfidence() *int {
	if c == nil {
		return nil
	}
	return c.Confidence
}

func (c *CommonProperties) GetLang() *string {
	if c == nil {
		return nil
	}
	return c.Lang
}

func (c *CommonProperties) GetExternalReferences() []*ExternalReference {
	if c == nil {
		return nil
	}
	return c.ExternalReferences
}

func (c *CommonProperties) GetObjectMarkingRefs() []*MarkingDefinition {
	if c == nil {
		return nil
	}
	return c.ObjectMarkingRefs
}

func (c *CommonProperties) GetGranularMarkings() []*GranularMarking {
	if c == nil {
		return nil
	}
	return c.GranularMarkings
}

func (c *CommonProperties) GetExtensions() map[string]any {
	if c == nil {
		return nil
	}
	return c.Extensions
}

func (c *CommonProperties) SpecVersion() string {
	return c.specVersion
}

func (c *CommonProperties) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CommonProperties) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetId(id Id) {
	c.Id = id
	c.require(commonPropertiesFieldId)
}

// SetCreatedByRef sets the CreatedByRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetCreatedByRef(createdByRef *Identity) {
	c.CreatedByRef = createdByRef
	c.require(commonPropertiesFieldCreatedByRef)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetCreated(created time.Time) {
	c.Created = created
	c.require(commonPropertiesFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetModified(modified time.Time) {
	c.Modified = modified
	c.require(commonPropertiesFieldModified)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetRevoked(revoked *bool) {
	c.Revoked = revoked
	c.require(commonPropertiesFieldRevoked)
}

// SetLabels sets the Labels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetLabels(labels []string) {
	c.Labels = labels
	c.require(commonPropertiesFieldLabels)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetConfidence(confidence *int) {
	c.Confidence = confidence
	c.require(commonPropertiesFieldConfidence)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetLang(lang *string) {
	c.Lang = lang
	c.require(commonPropertiesFieldLang)
}

// SetExternalReferences sets the ExternalReferences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetExternalReferences(externalReferences []*ExternalReference) {
	c.ExternalReferences = externalReferences
	c.require(commonPropertiesFieldExternalReferences)
}

// SetObjectMarkingRefs sets the ObjectMarkingRefs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetObjectMarkingRefs(objectMarkingRefs []*MarkingDefinition) {
	c.ObjectMarkingRefs = objectMarkingRefs
	c.require(commonPropertiesFieldObjectMarkingRefs)
}

// SetGranularMarkings sets the GranularMarkings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetGranularMarkings(granularMarkings []*GranularMarking) {
	c.GranularMarkings = granularMarkings
	c.require(commonPropertiesFieldGranularMarkings)
}

// SetExtensions sets the Extensions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommonProperties) SetExtensions(extensions map[string]any) {
	c.Extensions = extensions
	c.require(commonPropertiesFieldExtensions)
}

func (c *CommonProperties) UnmarshalJSON(data []byte) error {
	type embed CommonProperties
	var unmarshaler = struct {
		embed
		Created     *internal.DateTime `json:"created"`
		Modified    *internal.DateTime `json:"modified"`
		SpecVersion string             `json:"spec_version"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CommonProperties(unmarshaler.embed)
	c.Created = unmarshaler.Created.Time()
	c.Modified = unmarshaler.Modified.Time()
	if unmarshaler.SpecVersion != "2.1" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", c, "2.1", unmarshaler.SpecVersion)
	}
	c.specVersion = unmarshaler.SpecVersion
	extraProperties, err := internal.ExtractExtraProperties(data, *c, "spec_version")
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = nil
	return nil
}

func (c *CommonProperties) MarshalJSON() ([]byte, error) {
	type embed CommonProperties
	var marshaler = struct {
		embed
		Created     *internal.DateTime `json:"created"`
		Modified    *internal.DateTime `json:"modified"`
		SpecVersion string             `json:"spec_version"`
	}{
		embed:       embed(*c),
		Created:     internal.NewDateTime(c.Created),
		Modified:    internal.NewDateTime(c.Modified),
		SpecVersion: "2.1",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CommonProperties) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	externalReferenceFieldSourceName  = big.NewInt(1 << 0)
	externalReferenceFieldDescription = big.NewInt(1 << 1)
	externalReferenceFieldUrl         = big.NewInt(1 << 2)
	externalReferenceFieldHash        = big.NewInt(1 << 3)
	externalReferenceFieldExternalId  = big.NewInt(1 << 4)
)

type ExternalReference struct {
	// The source_name property specifies the name of the source that provided the external reference.
	SourceName string `json:"source_name" url:"source_name"`
	// The description property provides a human-readable explanation of the external reference.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The url property specifies the URL of the external reference.
	Url *string `json:"url,omitempty" url:"url,omitempty"`
	// The hash property specifies a hash value that uniquely identifies the external reference.
	Hash *string `json:"hash,omitempty" url:"hash,omitempty"`
	// The external_id property specifies an identifier used by the source of the external reference.
	ExternalId *string `json:"external_id,omitempty" url:"external_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ExternalReference) GetSourceName() string {
	if e == nil {
		return ""
	}
	return e.SourceName
}

func (e *ExternalReference) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ExternalReference) GetUrl() *string {
	if e == nil {
		return nil
	}
	return e.Url
}

func (e *ExternalReference) GetHash() *string {
	if e == nil {
		return nil
	}
	return e.Hash
}

func (e *ExternalReference) GetExternalId() *string {
	if e == nil {
		return nil
	}
	return e.ExternalId
}

func (e *ExternalReference) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ExternalReference) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetSourceName sets the SourceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalReference) SetSourceName(sourceName string) {
	e.SourceName = sourceName
	e.require(externalReferenceFieldSourceName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalReference) SetDescription(description *string) {
	e.Description = description
	e.require(externalReferenceFieldDescription)
}

// SetUrl sets the Url field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalReference) SetUrl(url *string) {
	e.Url = url
	e.require(externalReferenceFieldUrl)
}

// SetHash sets the Hash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalReference) SetHash(hash *string) {
	e.Hash = hash
	e.require(externalReferenceFieldHash)
}

// SetExternalId sets the ExternalId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalReference) SetExternalId(externalId *string) {
	e.ExternalId = externalId
	e.require(externalReferenceFieldExternalId)
}

func (e *ExternalReference) UnmarshalJSON(data []byte) error {
	type unmarshaler ExternalReference
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ExternalReference(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = nil
	return nil
}

func (e *ExternalReference) MarshalJSON() ([]byte, error) {
	type embed ExternalReference
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ExternalReference) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	granularMarkingFieldLang       = big.NewInt(1 << 0)
	granularMarkingFieldMarkingRef = big.NewInt(1 << 1)
	granularMarkingFieldSelectors  = big.NewInt(1 << 2)
)

type GranularMarking struct {
	// The lang property specifies the language used in the properties of the marking_definition object.
	Lang *string `json:"lang,omitempty" url:"lang,omitempty"`
	// The marking_ref property specifies the id property of the marking_definition object that applies to this object.
	MarkingRef *MarkingDefinition `json:"marking_ref,omitempty" url:"marking_ref,omitempty"`
	// The selectors property is an array of strings that represent the selectors that are used to apply the marking_definition object to this object.
	Selectors []string `json:"selectors" url:"selectors"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GranularMarking) GetLang() *string {
	if g == nil {
		return nil
	}
	return g.Lang
}

func (g *GranularMarking) GetMarkingRef() *MarkingDefinition {
	if g == nil {
		return nil
	}
	return g.MarkingRef
}

func (g *GranularMarking) GetSelectors() []string {
	if g == nil {
		return nil
	}
	return g.Selectors
}

func (g *GranularMarking) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GranularMarking) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GranularMarking) SetLang(lang *string) {
	g.Lang = lang
	g.require(granularMarkingFieldLang)
}

// SetMarkingRef sets the MarkingRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GranularMarking) SetMarkingRef(markingRef *MarkingDefinition) {
	g.MarkingRef = markingRef
	g.require(granularMarkingFieldMarkingRef)
}

// SetSelectors sets the Selectors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GranularMarking) SetSelectors(selectors []string) {
	g.Selectors = selectors
	g.require(granularMarkingFieldSelectors)
}

func (g *GranularMarking) UnmarshalJSON(data []byte) error {
	type unmarshaler GranularMarking
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GranularMarking(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = nil
	return nil
}

func (g *GranularMarking) MarshalJSON() ([]byte, error) {
	type embed GranularMarking
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GranularMarking) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type Id = string

var (
	identityFieldId                 = big.NewInt(1 << 0)
	identityFieldCreatedByRef       = big.NewInt(1 << 1)
	identityFieldCreated            = big.NewInt(1 << 2)
	identityFieldModified           = big.NewInt(1 << 3)
	identityFieldRevoked            = big.NewInt(1 << 4)
	identityFieldLabels             = big.NewInt(1 << 5)
	identityFieldConfidence         = big.NewInt(1 << 6)
	identityFieldLang               = big.NewInt(1 << 7)
	identityFieldExternalReferences = big.NewInt(1 << 8)
	identityFieldObjectMarkingRefs  = big.NewInt(1 << 9)
	identityFieldGranularMarkings   = big.NewInt(1 << 10)
	identityFieldExtensions         = big.NewInt(1 << 11)
	identityFieldType               = big.NewInt(1 << 12)
	identityFieldName               = big.NewInt(1 << 13)
	identityFieldDescription        = big.NewInt(1 << 14)
	identityFieldRoles              = big.NewInt(1 << 15)
	identityFieldIdentityClass      = big.NewInt(1 << 16)
)

type Identity struct {
	// The id property uniquely identifies this object.
	Id Id `json:"id" url:"id"`
	// The created_by_ref property specifies the id property of the identity object that describes the entity that created this object.
	CreatedByRef *Identity `json:"created_by_ref,omitempty" url:"created_by_ref,omitempty"`
	// The created property represents the time at which the object was originally created.
	Created time.Time `json:"created" url:"created"`
	// The modified property is only used by STIX Objects that support versioning and represents the time that this particular version of the object was last modified.
	Modified time.Time `json:"modified" url:"modified"`
	// The revoked property indicates whether this object has been revoked. If the revoked property is present and set to true, then the object has been revoked.
	Revoked *bool `json:"revoked,omitempty" url:"revoked,omitempty"`
	// The labels property is an array of strings that are used to categorize this object.
	Labels []string `json:"labels,omitempty" url:"labels,omitempty"`
	// The confidence property is an integer from 0 to 100 that represents the confidence that this object is accurate and valid.
	Confidence *int `json:"confidence,omitempty" url:"confidence,omitempty"`
	// The lang property specifies the language used in the properties of the object.
	Lang *string `json:"lang,omitempty" url:"lang,omitempty"`
	// The external_references property is an array of external references that are relevant to this object.
	ExternalReferences []*ExternalReference `json:"external_references,omitempty" url:"external_references,omitempty"`
	// The object_marking_refs property is an array of ids of marking_definition objects that apply to this object.
	ObjectMarkingRefs []*MarkingDefinition `json:"object_marking_refs,omitempty" url:"object_marking_refs,omitempty"`
	// The granular_markings property is an array of granular markings that are applied to this object.
	GranularMarkings []*GranularMarking `json:"granular_markings,omitempty" url:"granular_markings,omitempty"`
	// The extensions property is an object that contains custom properties or objects that extend the object.
	Extensions map[string]any `json:"extensions,omitempty" url:"extensions,omitempty"`
	// The value of this property MUST be identity.
	Type string `json:"type" url:"type"`
	// The name of this Identity. When referring to a specific entity (e.g., an individual or organization), this property SHOULD contain the canonical name of the specific entity.
	Name        string  `json:"name" url:"name"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The list of roles that this Identity performs. No open vocabulary is yet defined for this property.
	Roles         *string          `json:"roles,omitempty" url:"roles,omitempty"`
	IdentityClass *IdentityClassOv `json:"identity_class,omitempty" url:"identity_class,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	specVersion    string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *Identity) GetId() Id {
	if i == nil {
		return ""
	}
	return i.Id
}

func (i *Identity) GetCreatedByRef() *Identity {
	if i == nil {
		return nil
	}
	return i.CreatedByRef
}

func (i *Identity) GetCreated() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.Created
}

func (i *Identity) GetModified() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.Modified
}

func (i *Identity) GetRevoked() *bool {
	if i == nil {
		return nil
	}
	return i.Revoked
}

func (i *Identity) GetLabels() []string {
	if i == nil {
		return nil
	}
	return i.Labels
}

func (i *Identity) GetConfidence() *int {
	if i == nil {
		return nil
	}
	return i.Confidence
}

func (i *Identity) GetLang() *string {
	if i == nil {
		return nil
	}
	return i.Lang
}

func (i *Identity) GetExternalReferences() []*ExternalReference {
	if i == nil {
		return nil
	}
	return i.ExternalReferences
}

func (i *Identity) GetObjectMarkingRefs() []*MarkingDefinition {
	if i == nil {
		return nil
	}
	return i.ObjectMarkingRefs
}

func (i *Identity) GetGranularMarkings() []*GranularMarking {
	if i == nil {
		return nil
	}
	return i.GranularMarkings
}

func (i *Identity) GetExtensions() map[string]any {
	if i == nil {
		return nil
	}
	return i.Extensions
}

func (i *Identity) GetType() string {
	if i == nil {
		return ""
	}
	return i.Type
}

func (i *Identity) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *Identity) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *Identity) GetRoles() *string {
	if i == nil {
		return nil
	}
	return i.Roles
}

func (i *Identity) GetIdentityClass() *IdentityClassOv {
	if i == nil {
		return nil
	}
	return i.IdentityClass
}

func (i *Identity) SpecVersion() string {
	return i.specVersion
}

func (i *Identity) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *Identity) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetId(id Id) {
	i.Id = id
	i.require(identityFieldId)
}

// SetCreatedByRef sets the CreatedByRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetCreatedByRef(createdByRef *Identity) {
	i.CreatedByRef = createdByRef
	i.require(identityFieldCreatedByRef)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetCreated(created time.Time) {
	i.Created = created
	i.require(identityFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetModified(modified time.Time) {
	i.Modified = modified
	i.require(identityFieldModified)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetRevoked(revoked *bool) {
	i.Revoked = revoked
	i.require(identityFieldRevoked)
}

// SetLabels sets the Labels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetLabels(labels []string) {
	i.Labels = labels
	i.require(identityFieldLabels)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetConfidence(confidence *int) {
	i.Confidence = confidence
	i.require(identityFieldConfidence)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetLang(lang *string) {
	i.Lang = lang
	i.require(identityFieldLang)
}

// SetExternalReferences sets the ExternalReferences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetExternalReferences(externalReferences []*ExternalReference) {
	i.ExternalReferences = externalReferences
	i.require(identityFieldExternalReferences)
}

// SetObjectMarkingRefs sets the ObjectMarkingRefs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetObjectMarkingRefs(objectMarkingRefs []*MarkingDefinition) {
	i.ObjectMarkingRefs = objectMarkingRefs
	i.require(identityFieldObjectMarkingRefs)
}

// SetGranularMarkings sets the GranularMarkings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetGranularMarkings(granularMarkings []*GranularMarking) {
	i.GranularMarkings = granularMarkings
	i.require(identityFieldGranularMarkings)
}

// SetExtensions sets the Extensions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetExtensions(extensions map[string]any) {
	i.Extensions = extensions
	i.require(identityFieldExtensions)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetType(type_ string) {
	i.Type = type_
	i.require(identityFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetName(name string) {
	i.Name = name
	i.require(identityFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetDescription(description *string) {
	i.Description = description
	i.require(identityFieldDescription)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetRoles(roles *string) {
	i.Roles = roles
	i.require(identityFieldRoles)
}

// SetIdentityClass sets the IdentityClass field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Identity) SetIdentityClass(identityClass *IdentityClassOv) {
	i.IdentityClass = identityClass
	i.require(identityFieldIdentityClass)
}

func (i *Identity) UnmarshalJSON(data []byte) error {
	type embed Identity
	var unmarshaler = struct {
		embed
		Created     *internal.DateTime `json:"created"`
		Modified    *internal.DateTime `json:"modified"`
		SpecVersion string             `json:"spec_version"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = Identity(unmarshaler.embed)
	i.Created = unmarshaler.Created.Time()
	i.Modified = unmarshaler.Modified.Time()
	if unmarshaler.SpecVersion != "2.1" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", i, "2.1", unmarshaler.SpecVersion)
	}
	i.specVersion = unmarshaler.SpecVersion
	extraProperties, err := internal.ExtractExtraProperties(data, *i, "spec_version")
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = nil
	return nil
}

func (i *Identity) MarshalJSON() ([]byte, error) {
	type embed Identity
	var marshaler = struct {
		embed
		Created     *internal.DateTime `json:"created"`
		Modified    *internal.DateTime `json:"modified"`
		SpecVersion string             `json:"spec_version"`
	}{
		embed:       embed(*i),
		Created:     internal.NewDateTime(i.Created),
		Modified:    internal.NewDateTime(i.Modified),
		SpecVersion: "2.1",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *Identity) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	killChainPhaseFieldKillChainName = big.NewInt(1 << 0)
	killChainPhaseFieldPhaseName     = big.NewInt(1 << 1)
)

type KillChainPhase struct {
	// The kill_chain_name property specifies the name of the kill chain to which the phase belongs.
	KillChainName string `json:"kill_chain_name" url:"kill_chain_name"`
	// The phase_name property specifies the name of the phase within the kill chain.
	PhaseName string `json:"phase_name" url:"phase_name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (k *KillChainPhase) GetKillChainName() string {
	if k == nil {
		return ""
	}
	return k.KillChainName
}

func (k *KillChainPhase) GetPhaseName() string {
	if k == nil {
		return ""
	}
	return k.PhaseName
}

func (k *KillChainPhase) GetExtraProperties() map[string]interface{} {
	if k == nil {
		return nil
	}
	return k.extraProperties
}

func (k *KillChainPhase) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetKillChainName sets the KillChainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KillChainPhase) SetKillChainName(killChainName string) {
	k.KillChainName = killChainName
	k.require(killChainPhaseFieldKillChainName)
}

// SetPhaseName sets the PhaseName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KillChainPhase) SetPhaseName(phaseName string) {
	k.PhaseName = phaseName
	k.require(killChainPhaseFieldPhaseName)
}

func (k *KillChainPhase) UnmarshalJSON(data []byte) error {
	type unmarshaler KillChainPhase
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*k = KillChainPhase(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *k)
	if err != nil {
		return err
	}
	k.extraProperties = extraProperties
	k.rawJSON = nil
	return nil
}

func (k *KillChainPhase) MarshalJSON() ([]byte, error) {
	type embed KillChainPhase
	var marshaler = struct {
		embed
	}{
		embed: embed(*k),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, k.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (k *KillChainPhase) String() string {
	if k == nil {
		return "<nil>"
	}
	if len(k.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(k.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(k); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", k)
}

var (
	markingDefinitionFieldType = big.NewInt(1 << 0)
	markingDefinitionFieldName = big.NewInt(1 << 1)
)

type MarkingDefinition struct {
	// The type property identifies the type of object. The value of this property MUST be marking_definition.
	Type string  `json:"type" url:"type"`
	Name *string `json:"name,omitempty" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MarkingDefinition) GetType() string {
	if m == nil {
		return ""
	}
	return m.Type
}

func (m *MarkingDefinition) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MarkingDefinition) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MarkingDefinition) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarkingDefinition) SetType(type_ string) {
	m.Type = type_
	m.require(markingDefinitionFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarkingDefinition) SetName(name *string) {
	m.Name = name
	m.require(markingDefinitionFieldName)
}

func (m *MarkingDefinition) UnmarshalJSON(data []byte) error {
	type unmarshaler MarkingDefinition
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MarkingDefinition(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = nil
	return nil
}

func (m *MarkingDefinition) MarshalJSON() ([]byte, error) {
	type embed MarkingDefinition
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MarkingDefinition) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
