// This file was auto-generated by Fern from our API Definition.

package management

type AccountOptions struct {
	// Tokens are created for this account with this duration as their TTL. Defaults to 1 year.
	TokenTtl *string `json:"token_ttl,omitempty"`
}
