// Code generated by Fern. DO NOT EDIT.

package credentials

import (
    context "context"
    http "net/http"

    management "github.com/synqly/go-sdk/client/management"
    core "github.com/synqly/go-sdk/client/management/core"
    internal "github.com/synqly/go-sdk/client/management/internal"
    option "github.com/synqly/go-sdk/client/management/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) List(
    ctx context.Context,
    ownerId management.Id,
    request *management.ListCredentialsRequest,
    opts ...option.RequestOption,
) (*core.Response[*management.ListCredentialsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v",
        ownerId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.ListCredentialsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.ListCredentialsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Get(
    ctx context.Context,
    ownerId management.Id,
    credentialId management.CredentialId,
    opts ...option.RequestOption,
) (*core.Response[*management.GetCredentialResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v/%v",
        ownerId,
        credentialId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.GetCredentialResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.GetCredentialResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Lookup(
    ctx context.Context,
    credentialId management.CredentialId,
    opts ...option.RequestOption,
) (*core.Response[*management.LookupCredentialResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/lookup/%v",
        credentialId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.LookupCredentialResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.LookupCredentialResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Create(
    ctx context.Context,
    ownerId management.Id,
    request *management.CreateCredentialRequest,
    opts ...option.RequestOption,
) (*core.Response[*management.CreateCredentialResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v",
        ownerId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.CreateCredentialResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.CreateCredentialResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Update(
    ctx context.Context,
    ownerId management.Id,
    credentialId management.CredentialId,
    request management.UpdateCredentialRequest,
    opts ...option.RequestOption,
) (*core.Response[*management.UpdateCredentialResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v/%v",
        ownerId,
        credentialId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.UpdateCredentialResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPut,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.UpdateCredentialResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Patch(
    ctx context.Context,
    ownerId management.Id,
    credentialId management.CredentialId,
    request []*management.PatchOperation,
    opts ...option.RequestOption,
) (*core.Response[*management.PatchCredentialResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v/%v",
        ownerId,
        credentialId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *management.PatchCredentialResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPatch,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*management.PatchCredentialResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Delete(
    ctx context.Context,
    ownerId management.Id,
    credentialId management.CredentialId,
    opts ...option.RequestOption,
) (*core.Response[any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/credentials/%v/%v",
        ownerId,
        credentialId,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodDelete,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            ErrorDecoder: internal.NewErrorDecoder(management.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: nil,
    }, nil
}

