// This file was auto-generated by Fern from our API Definition.

package events

// The Compliance object contains information about compliance requirements related of a finding generated by security tool.
type Compliance struct {
	// A list of applicable compliance requirements for which this finding is related to.
	Requirements *[]string `json:"requirements,omitempty"`
	// The event status, normalized to the caption of the status_id value. In the case of 'Other', it is defined by the event source.
	Status *string `json:"status,omitempty"`
	// The status details contains additional information about the event outcome.
	StatusDetail *string `json:"status_detail,omitempty"`
}
