// This file was auto-generated by Fern from our API Definition.

package events

// The DCE/RPC, or Distributed Computing Environment/Remote Procedure Call, object describes the remote procedure call system for distributed computing environments. Defined by D3FEND <a target='_blank' href='https://d3fend.mitre.org/dao/artifact/d3f:RemoteProcedureCall/'>d3f:RemoteProcedureCall</a>.
type DceRpc struct {
	// The request command (e.g. REQUEST, BIND).
	Command *string `json:"command,omitempty"`
	// The reply to the request command (e.g. RESPONSE, BINDACK or FAULT).
	CommandResponse *string `json:"command_response,omitempty"`
	// The list of interface flags.
	Flags []string `json:"flags,omitempty"`
	// The list of DCE/RPC interfaces
	NetworkInterfaces []*NetworkInterface `json:"network_interfaces,omitempty"`
	// An operation number used to identify a specific remote procedure call (RPC) method or a method in an interface.
	Opnum *int `json:"opnum,omitempty"`
}
