// This file was auto-generated by Fern from our API Definition.

package events

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// Category ID. The category unique identifier of the event.
type FileActivityCategoryUid uint8

const (
	// System Activity events.
	FileActivityCategoryUidSystemActivity FileActivityCategoryUid = iota + 1
)

func (f FileActivityCategoryUid) String() string {
	switch f {
	default:
		return strconv.Itoa(int(f))
	case FileActivityCategoryUidSystemActivity:
		return "1"
	}
}

func (f FileActivityCategoryUid) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", f.String())), nil
}

func (f *FileActivityCategoryUid) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "1":
		value := FileActivityCategoryUidSystemActivity
		*f = value
	}
	return nil
}
