// This file was auto-generated by Fern from our API Definition.

package events

// The Kernel Resource object provides information about a specific kernel resource, including its name and type. It describes essential attributes associated with a resource managed by the kernel of an operating system. Defined by D3FEND <a target='_blank' href='https://d3fend.mitre.org/dao/artifact/d3f:Kernel/'>d3f:Kernel</a>.
type Kernel struct {
	// The indication of whether the object is part of the operating system.
	IsSystem *bool `json:"is_system,omitempty"`
	// The name of the kernel resource.
	Name string `json:"name"`
	// The full path of the kernel resource.
	Path *string `json:"path,omitempty"`
	// The system call that was invoked.
	SystemCall *string `json:"system_call,omitempty"`
	// The type of the kernel resource.
	Type *string `json:"type,omitempty"`
	// The type of the kernel resource.
	TypeId KernelTypeId `json:"type_id,omitempty"`
}
