// This file was auto-generated by Fern from our API Definition.

package events

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// IP Version ID. The Internet Protocol version identifier.
type NetworkConnectionInfoProtocolVerId uint8

const (
	NetworkConnectionInfoProtocolVerIdUnknown NetworkConnectionInfoProtocolVerId = iota + 1
	NetworkConnectionInfoProtocolVerIdInternetProtocolversion4IPv4
	NetworkConnectionInfoProtocolVerIdInternetProtocolversion6IPv6
	NetworkConnectionInfoProtocolVerIdOther
)

func (n NetworkConnectionInfoProtocolVerId) String() string {
	switch n {
	default:
		return strconv.Itoa(int(n))
	case NetworkConnectionInfoProtocolVerIdUnknown:
		return "0"
	case NetworkConnectionInfoProtocolVerIdInternetProtocolversion4IPv4:
		return "4"
	case NetworkConnectionInfoProtocolVerIdInternetProtocolversion6IPv6:
		return "6"
	case NetworkConnectionInfoProtocolVerIdOther:
		return "99"
	}
}

func (n NetworkConnectionInfoProtocolVerId) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", n.String())), nil
}

func (n *NetworkConnectionInfoProtocolVerId) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "0":
		value := NetworkConnectionInfoProtocolVerIdUnknown
		*n = value
	case "4":
		value := NetworkConnectionInfoProtocolVerIdInternetProtocolversion4IPv4
		*n = value
	case "6":
		value := NetworkConnectionInfoProtocolVerIdInternetProtocolversion6IPv6
		*n = value
	case "99":
		value := NetworkConnectionInfoProtocolVerIdOther
		*n = value
	}
	return nil
}
