// Code generated by Fern. DO NOT EDIT.

package edr

import (
    bytes "bytes"
    context "context"
    io "io"
    http "net/http"

    engine "github.com/synqly/go-sdk/client/engine"
    core "github.com/synqly/go-sdk/client/engine/core"
    internal "github.com/synqly/go-sdk/client/engine/internal"
    option "github.com/synqly/go-sdk/client/engine/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) QueryEndpoints(
    ctx context.Context,
    request *engine.QueryEndpointsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryEndpointsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/endpoints"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryEndpointsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryEndpointsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetEndpoint(
    ctx context.Context,
    id engine.Id,
    request *engine.GetEndpointRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.GetEndpointResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/edr/endpoints/%v",
        id,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.GetEndpointResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.GetEndpointResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ExecuteCommand(
    ctx context.Context,
    uid engine.Id,
    request *engine.ExecuteCommandRequestInput,
    opts ...option.RequestOption,
) (*core.Response[*engine.ExecuteCommandResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/edr/endpoints/%v/actions/execute-command",
        uid,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.ExecuteCommandResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.ExecuteCommandResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) RetrieveFile(
    ctx context.Context,
    uid engine.Id,
    request *engine.RetrieveFileRequest,
    opts ...option.RequestOption,
) (*core.Response[io.Reader], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/edr/endpoints/%v/actions/retrieve-file",
        uid,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    response := bytes.NewBuffer(nil)
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[io.Reader]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryApplications(
    ctx context.Context,
    request *engine.QueryApplicationsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryApplicationsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/applications"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryApplicationsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryApplicationsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) NetworkQuarantine(
    ctx context.Context,
    request *engine.NetworkQuarantineRequestInput,
    opts ...option.RequestOption,
) (*core.Response[*engine.NetworkQuarantineResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/endpoints/actions/quarantine"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.NetworkQuarantineResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.NetworkQuarantineResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryThreatevents(
    ctx context.Context,
    request *engine.QueryThreatsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryThreatsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/threats"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryThreatsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryThreatsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryAlerts(
    ctx context.Context,
    request *engine.QueryAlertsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryAlertsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/alerts"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryAlertsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryAlertsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryIocs(
    ctx context.Context,
    request *engine.QueryIocsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryIocsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/iocs"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryIocsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryIocsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CreateIocs(
    ctx context.Context,
    request *engine.CreateIocsRequestInput,
    opts ...option.RequestOption,
) (*core.Response[*engine.CreateIocsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/iocs"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.CreateIocsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.CreateIocsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) DeleteIocs(
    ctx context.Context,
    request *engine.DeleteIocsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.DeleteIocsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/iocs"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.DeleteIocsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodDelete,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.DeleteIocsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryPostureScore(
    ctx context.Context,
    request *engine.QueryPostureScoreRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryPostureScoreResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/posture_score"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryPostureScoreResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryPostureScoreResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) QueryEdrEvents(
    ctx context.Context,
    request *engine.QueryEdrEventsRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.QueryEdrEventsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := baseURL + "/v1/edr/edr_events"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.QueryEdrEventsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.QueryEdrEventsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetThreatNotes(
    ctx context.Context,
    threatId string,
    request *engine.GetThreatNotesRequest,
    opts ...option.RequestOption,
) (*core.Response[*engine.GetThreatNotesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/edr/threats/%v/notes",
        threatId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.GetThreatNotesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.GetThreatNotesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CreateThreatNote(
    ctx context.Context,
    threatId string,
    request *engine.CreateThreatNoteRequestInput,
    opts ...option.RequestOption,
) (*core.Response[*engine.CreateThreatNoteResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "https://api.synqly.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v1/edr/threats/%v/notes",
        threatId,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *engine.CreateThreatNoteResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(engine.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*engine.CreateThreatNoteResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

