// Code generated by Fern. DO NOT EDIT.

package v180

// Email address. For example:<br><code>john_doe@example.com</code>.
type EmailAddress = string

// File name. For example:<br><code>text-file.txt</code>.
type FileName = string

// The full path to the file. For example: For example:<br><code>c:\windows\system32\svchost.exe</code>.
type FilePath = string

// Fingerprint. A value, in any format, that maps an arbitrarily large data item to a much shorter string that uniquely identifies the original data. Examples include cryptographic hashing of a file, code signing, and Network Protocol Fingerprinting (NPF).<p><b>Note about name.</b> The type name <code>file_hast_t</code> and the caption &quot;Hash&quot; are used for legacy reasons. This type has been generalized from a file hash to a general fingerprint. The existing type name and caption were retained for backwards compatibility.
type Hash = string

// Unique name assigned to a device connected to a computer network. It may be a fully qualified domain name (FQDN). For example:<br><code>r2-d2.example.com.</code>,<br><code>mx.example.com</code>
type Hostname = string

// Internet Protocol address (IP address), in either IPv4 or IPv6 format. For example:<br><code>192.168.200.24</code>, <br> <code>2001:0db8:85a3:0000:0000:8a2e:0370:7334</code>.
type IpAddress = string

// Media Access Control (MAC) address. For example:<br><code>18:36:F3:98:4F:9A</code>.
type MacAddress = string

// The TCP/UDP port number. For example:<br><code>80</code>,<br><code>22</code>.
type Port = int

// Process name. For example:<br><code>Notepad</code>.
type ProcessName = string

// Resource unique identifier. For example, S3 Bucket name or EC2 Instance ID.
type ResourceUid = string

// The subnet represented in a CIDR notation, using the format network_address/prefix_length. The network_address can be in either IPv4 or IPv6 format. The prefix length indicates the number of bits used for the network portion, and the remaining bits are available for host addresses within that subnet. For example:<br><code>192.168.1.0/24</code>,<br><code>2001:0db8:85a3:0000::/64</code>
type Subnet = string

// The timestamp format is the number of milliseconds since the Epoch 01/01/1970 00:00:00 UTC. For example:<br><code>1618524549901</code>.
type Timestamp = int

// Uniform Resource Locator (URL) string. For example:<br><code>http://www.example.com/download/trouble.exe</code>.
type UrlString = string

// User name. For example:<br><code>john_doe</code>.
type UserName = string
